### ISSUE TITLE
[Feature Request] Calculate and show mobs/pulls {HealthPoints/TrashPercent} as a cost-per-value

### ISSUE THREAD

**Issue by RamyRafik** [Nnoggie/MythicDungeonTools#144]
To help route authors decide which mobs are worth pulling, it will be helpful to show how much HealthPoints each mob/pull have has (as a rough indication of how fast they would die) divided by Percent they give.
This can then show in the MDT mobs tooltips and in-game tooltips.

Showing {HP/Value} instead of {Value/HP} would show less decimal spaces.

Authors/leaders should then aim at choosing mobs/pulls with lowest cost-per-value

**Comment by daveybtw** [comment]
Icons already show HP values, the routes are not always the same and the worth criteria is always discretion of the group and skills from the mobs (Some mobs have less hp but are more painful to pull than others cause of skills/other mobs with them)
