### ISSUE TITLE
Posible code change in plater mod after recently re-branding

### ISSUE THREAD

**Issue by rusomenace** [Nnoggie/MythicDungeonTools#149]
I have a mod in plater link to ex method dungeon tool, part of the code points directly to MDT addon:

        if MethodDungeonTools ~= nil and MethodDungeonTools.GetEnemyForces ~= nil then
            local mobPercentageString = ""
            local weight = nil;
            local isTeeming = envTable.isTeeming()
            local npcId = unitFrame.namePlateNpcId
            local count, max, maxTeeming, teemingCount = MethodDungeonTools:GetEnemyForces(npcId)

Mob percetange in keys is still working but i will like to ask if this is going to change to MythicDungeonTool so i may have to change this part of the code in plater mod.
Linto the mod: https://wago.io/M8ejNxoo_

TY

**Comment by Nnoggie** [comment]
`MethodDungeonTools:GetEnemyForces(npcId)`
will work until 9.0
The new way to call this function now is:
`MDT:GetEnemyForces(npcId)`
