### ISSUE TITLE
Feature idea: a mini mdt you can toggle on during a run

### ISSUE THREAD

**Issue by Herdrage** [Nnoggie/MythicDungeonTools#152]
I was thinking it would be cool and useful if there was portable map of our routes we make say the same size as the zone map wow uses. Basically your created route in MDT but just the map and not interactable outside of maybe being movable and locking in position, being able to zoom in and out would be a plus too. Maybe it could read when you change sub zones inside a dungeon and automatically switch to that map?

I think it could be useful for people that don't main tanking or push keys very often where they could use a little guide with their route as they go.

**Comment by st4l** [comment]
I actually do this currently by resizing and using the keybind to open it... when its not maximized and you resized it to the minimum and you move it to the right so the pulls are out of screen, you can use it even though it covers a quarter of the screen... I was thinking of contributing a PR to add a keybind to open it as "minimap" like the normal map when you press Ctrl-Shift-M, if anyone can guide me on the basics (hop on discord for a bit with me for a short code walkthrough) I can give it a try

**Comment by Nnoggie** [comment]
https://www.curseforge.com/wow/addons/mdt-guide

**Comment by st4l** [comment]
@Nnoggie yes, thats the one I was referring to, but the minimum size is almost a quarter of the screen, and it would be nice to have a keybinding to put it into that mode. Just like the World Map, it has 3 sizes: full screen, the one with the quest list, and a  "Zone Map" view without the quests (in this case it would be without the pulls).

**Comment by st4l** [comment]
NVM, I didn't mean that addon, I thought that link was to a "Guide to MDT" tutorial... in any case, I think the feature idea is a good one to add to the base MDT addon.
