### ISSUE TITLE
Possible ElvUI Skinning Error

### ISSUE THREAD

**Issue by Repooc** [Nnoggie/MythicDungeonTools#156]
Hey Nnoggie,
Just a developer for Shadow & Light and was trying to find an issue a user is having conflicting with our 2 addons at the same time and while I was looking through your code base to see where the possible issue is I came across your ElvUI Skinning section in MythicDungeonTools.lua lines 4867-4885 on version 3.1.0
On line 4879 you reference colorAlpha variable but the reference is wrong.  Should be `ElvUI[1].db.tooltip.colorAlpha`
I didnt test it or anything but feel free to test.

**Comment by Nnoggie** [comment]
Is this on Retail? I cannot reproduce this issue. 
`ElvUI[1].db.tooltip.colorAlpha` does not exist for me whereas `ElvUI[1].tooltip.colorAlpha` works fine.

![image](https://user-images.githubusercontent.com/27819512/91901330-5b5d8700-eca0-11ea-9d2b-6593fd4ebad2.png)

**Comment by Nnoggie** [comment]
Both references seem to work on my end (No Shadow and Light)
Are you sure this is an issue on MDTs side?
![image](https://user-images.githubusercontent.com/27819512/91901625-c909b300-eca0-11ea-9954-8ded243e4905.png)
