### ISSUE TITLE
Missing dependency linking it to main addon in .toc

### ISSUE THREAD

**Issue by casperstorm** [Nnoggie/MythicDungeonTools#158]
Hello,

I am currently creating a [Addon Manager](https://github.com/casperstorm/ajour/) and while parsing the `.toc` files I've noticed that MythicDungeonTools and MethodDungeonTools does not contains a dependency link: [MethodDungeonTools.toc](https://github.com/Nnoggie/MythicDungeonTools/blob/master/MDTStub/MethodDungeonTools.toc).

I would propose that you add `## RequiredDeps: MythicDungeonTools` to [MethodDungeonTools.toc](https://github.com/Nnoggie/MythicDungeonTools/blob/master/MDTStub/MethodDungeonTools.toc).

This would also mean that my addon, and other third party addon managers, knows that it's a helper addon, and thereby can determine which is the "parent" and only show that.

**Comment by Nnoggie** [comment]
MethodDungeonTools is the old name of MythicDungeonTools and every reference to it will be removed in this project in the 9.0 prepatch. The curseforge / twitch packaged download currently comes with a stub to overwrite old folder structures so the user does not experience any issues after updating.

**Comment by casperstorm** [comment]
Okay, so it seems the issue will be fixed in 9.x if the folder eventually will be removed. Thank you.

**Comment by Nnoggie** [comment]
fixed in 6a10505ec681b1940e135d6b9f2394a344763b69
