### ISSUE TITLE
Shadowlands: 9.0.1 SetBackdrop error

### ISSUE THREAD

**Issue by yoshimo** [Nnoggie/MythicDungeonTools#160]
Message: ...onTools\libs\LibUIDropDownMenu\LibUIDropDownMenu.lua line 223:
   attempt to call method 'SetBackdrop' (a nil value)
Debug:
   [string "@MythicDungeonTools\libs\LibUIDropDownMenu\LibUIDropDownMenu.lua"]:223: creatre_UIDropDownList()
   [string 

You should check for updates in that lib

**Comment by Nnoggie** [comment]
fixed
