### ISSUE TITLE
Ask for Language selection

### ISSUE THREAD

**Issue by ghost** [Nnoggie/MythicDungeonTools#162]
before the new name of addon, the language was english and i think it's better for communicate with other people.
My game is in french so Mythic Dungeon Tool is in french.
Can you add a feature to select language ?

**Comment by masonen** [comment]
Language Switcher was commented out by @Nnoggie on 2020-07-05 

Im not sure if it was just not working or is unwanted?

Could you eleborate that @Nnoggie? ill be happy to try to help on that if it is just not working.

**Comment by Nnoggie** [comment]
the implementation needs work to function properly but is in theory doable

**Comment by Nnoggie** [comment]
The amount of work it would take to make this functionality feasible is gigantic. Therefore i am closing this and will not be pursuing this. A simple workaround is possible in the following way:  Head to the Locales folder in MDT and choose which language you want to run.  Remove the first 3 lines of Lua code in that file. Now head over to the file coresponding to the language of your client and change the first 3 lines of Lua code to:
```lua
if true then
  return
end
```
