### ISSUE TITLE
3.2.8 missing AceAddon and LibDeflate

### ISSUE THREAD

**Issue by zgavin** [Nnoggie/MythicDungeonTools#174]
The release zip on curseforge is missing these libraries in the `libs` folder.    This causes load errors, although the addon seems to work if another addon supplies the libs.

Thanks for all your work on this addon!

**Comment by BradCOnGitHub** [comment]
I made a PR for what I did to fix it: https://github.com/Nnoggie/MythicDungeonTools/pull/173

**Comment by Nnoggie** [comment]
fixed
