### ISSUE TITLE
[BUG] You can't toggle GameMenu by clicking MainMenuMicroButton in combat

### ISSUE THREAD

**Issue by siweia** [Nnoggie/MythicDungeonTools#176]
Disable all addons, and only have MDT enabled.
Once you in combat, you can no longer open the GameMenu thru micro buttons.

**Comment by Nnoggie** [comment]
This is an error in LibUIDropDownMenu. It has been reported and will hopefully be fixed soon.

**Comment by Nnoggie** [comment]
fixed in 3.3.1
