### ISSUE TITLE
No spells in enemy info

### ISSUE THREAD

**Issue by Tomicolo** [Nnoggie/MythicDungeonTools#177]
Hello,

I can't see any spells in enemy info in Shadowlands (and Legion) dungeons. Those in BFA are working fine. It is a fresh installation of the addon. I even tried to re-install the addon and disable all other addons, neither fixed the issue.

![image](https://user-images.githubusercontent.com/75430768/101023181-affbf100-3572-11eb-8e3b-4e97154f1460.png)

**Comment by Tomicolo** [comment]
Update: Just ran through a Necrotic wake and the spells suddenly appeared for this dungeon in the addon.
If this is some sort of " database auto-update", then this is not an issue but a good feature. Nevertheless, no spells are visible before I run the dungeon, so no database is available on clean install.

**Comment by Nnoggie** [comment]
Spells are currently automatically collected and shared with all group members. In a future update this data will be made persistent and the collection turned off.
