### ISSUE TITLE
DataCollection.lua:256: bad argument #1 to 'unpack' (table expected, got string)

### ISSUE THREAD

**Issue by zmoose** [Nnoggie/MythicDungeonTools#178]
8x MythicDungeonTools\DataCollection.lua:256: bad argument #1 to 'unpack' (table expected, got string)
[string "=[C]"]: in function `unpack'
[string "@MythicDungeonTools\DataCollection.lua"]:256: in function `MergeReceiveData'
[string "@MythicDungeonTools\Transmission.lua"]:275: in function `?'
[string "@TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@AnnounceRare\Libraries\Ace3\AceComm-3.0\AceComm-3.0-12.lua"]:218: in function `OnReceiveMultipartLast'
[string "@AnnounceRare\Libraries\Ace3\AceComm-3.0\AceComm-3.0-12.lua"]:256: in function <...ounceRare\Libraries\Ace3\AceComm-3.0\AceComm-3.0.lua:246>

**Comment by abdes** [comment]
Message: ...terface\AddOns\MythicDungeonTools\DataCollection.lua:259: attempt to index field 'dataCollection' (a nil value)
Time: Thu Dec 10 17:01:01 2020
Count: 1
Stack: ...terface\AddOns\MythicDungeonTools\DataCollection.lua:259: attempt to index field 'dataCollection' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface\AddOns\MythicDungeonTools\DataCollection.lua"]:259: in function `MergeReceiveData'
[string "@Interface\AddOns\MythicDungeonTools\Transmission.lua"]:275: in function `?'
[string "@Interface\AddOns\!KalielsTracker\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...ker\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\!KalielsTracker\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ker\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\!KalielsTracker\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\AceComm-3.0\AceComm-3.0.lua"]:218: in function `OnReceiveMultipartLast'
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\AceComm-3.0\AceComm-3.0.lua"]:256: in function <...Ons\ElvUI\Libraries\Ace3\AceComm-3.0\AceComm-3.0.lua:246>

Locals: <none>
