### ISSUE TITLE
Importing tool overwriting other imports. 

### ISSUE THREAD

**Issue by ThYr0N** [Nnoggie/MythicDungeonTools#183]
When you import a second "run" all the other imports became the one imported.

Not sure if I'm doing something wrong but after trying to add the 8 runs from Dratnos from here https://raider.io/news/142-the-weekly-route-prideful-survival-guide I ended up with 8 of the same import.

Thanks.

**Comment by darkscion0** [comment]
Same issue here. I import one guide, it creates it with the proper name. I then import another one and it creates the new import but also changes the previous one to the most recently imported one. 

I've tried doing a reloadui and switching back to the default dungeon run between imports and the same thing happens.
