### ISSUE TITLE
Plaguefall issue

### ISSUE THREAD

**Issue by Pitboul19** [Nnoggie/MythicDungeonTools#184]
Hi,

When I open plagurfall map, the whole map is in flashy green ! The problem is only in "Plaguefall" not in "The festering sanctum"
Please can you fix it ?

Best regards,
Pitboul19

**Comment by qkjlu** [comment]
Same issue for me

**Comment by tomrus88** [comment]
https://github.com/Nnoggie/MythicDungeonTools/issues/179 this fix works
