### ISSUE TITLE
[Feature Request] Hideable sidebar and map follow player

### ISSUE THREAD

**Issue by xXdRaGoNrIdDeRXx** [Nnoggie/MythicDungeonTools#203]
I would love to have the ability to hide the right side bar and only show the map in sort of a read only view mode as my main usage is leaving it up during the dungeon, also having it auto swap to the correct floor like in Theatre of Pain would be awesome.

**Comment by masonen** [comment]
So thats like 2 Feature requests. Would you mind to split those up?

I cann see a value in both but there is no reason they need to be connected in a single feature request
