### ISSUE TITLE
Import LUA Error

### ISSUE THREAD

**Issue by flow0284** [Nnoggie/MythicDungeonTools#204]
With Version 3.4.5 (Curse) this LUA Error pops up when trying to import, rename or delete:

`1x ...aceMythicDungeonTools\MythicDungeonTools-3.4.5.lua:2637: attempt to index field 'dataImportDialog' (a nil value)
[string "@MythicDungeonTools\MythicDungeonTools-3.4.5.lua"]:2637: in function `HideAllDialogs'
[string "@MythicDungeonTools\MythicDungeonTools-3.4.5.lua"]:2642: in function `OpenImportPresetDialog'
[string "@MythicDungeonTools\MythicDungeonTools-3.4.5.lua"]:1291: in function <...aceMythicDungeonTools\MythicDungeonTools.lua:1290>
[string "=[C]"]: ?
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Ace3\AceGUI-3.0-41\widgets\AceGUIWidget-Button.lua"]:22: in function <...dOns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:19>`

**Comment by Nnoggie** [comment]
fixed
