### ISSUE TITLE
Sanguine Depths: Wrong Add-Group connection

### ISSUE THREAD

**Issue by xziino** [Nnoggie/MythicDungeonTools#207]
Hi,

found out that the very first "Gluttonous Tick" is pullable without the rest of the group stated in MDI, which leads to a potential skip there. Would be nice if that one mob gets seperated from that group for a correct % (in case u wanna skip). 

Or even the possibilty to manually reasign add groups in general?

https://imgur.com/a/O6WKgA6

Cheers and thx for the great work!

**Comment by mstinsky** [comment]
You can also select single mobs by holding the ctrl while selecting them.

**Comment by Nnoggie** [comment]
fixed
