### ISSUE TITLE
Sanguine Depths: Missing one or two Ravenous Dreadbat

### ISSUE THREAD

**Issue by Enkaf** [Nnoggie/MythicDungeonTools#211]
Hi! Probably miss one or two Ravenous Dreadbat in Sanguine Depths (I'm not sure how many, sorry), but there are more than one.

![image](https://user-images.githubusercontent.com/28902145/104124138-fde1f100-5389-11eb-8cce-0950d993b876.png)

**Comment by Nnoggie** [comment]
added a few bats 👍
