### ISSUE TITLE
The Necrotic Wake count seems off

### ISSUE THREAD

**Issue by Lavick81** [Nnoggie/MythicDungeonTools#214]
When following this route, https://wago.io/v3njzQefp , on a plus 2 I keep coming up just under 100% and we have to go back and pull the Corpse Harvester I to make the count needed.

**Comment by Nnoggie** [comment]
If you find that certain enemies are missing or have wrong count values in MDT, find the specifics and point them out. Simply saying that your route did not net you 100% count is not productive feedback.
