### ISSUE TITLE
[Feature Request] electron based stand-alone version

### ISSUE THREAD

**Issue by dominicrico** [Nnoggie/MythicDungeonTools#215]
If we woud have a stand-alone version, you could have it open all the time on a second screen. Most of the people have a multi screen setup, i guess. So this would be nice addition.

There seems to be an easy way to have it up and running.
https://medium.com/@IAmRyanSquared/web-and-web-like-development-with-lua-fdfca30282a3

**Comment by Nnoggie** [comment]
Not planning to do this.
