### ISSUE TITLE
New addon working together with mythic dungeon tools

### ISSUE THREAD

**Issue by aPanfaloneDev** [Nnoggie/MythicDungeonTools#216]
Hello, I was thinking about creating an addon that highlights the mobs that you mark in mythic dungeon tools. So you can see while playing without having to open the MDT UI to see if that mobs are the ones that you have to kill or you can just avoid them,

Is just to help to my personals needs. Is this possible? is possible to access to the mob id that mythic dungeon tools save? is possible to highlight or mark the mobs? I'm new creating addons but If you have a moment to talk about this, that would be awesome.

Thanks in advance.

**Comment by aPanfaloneDev** [comment]
Please, i really need help with this

**Comment by Nnoggie** [comment]
not possible without guesswork/heuristics
