### ISSUE TITLE
! for wrong week showing on correct week

### ISSUE THREAD

**Issue by DBQC** [Nnoggie/MythicDungeonTools#218]
![image](https://user-images.githubusercontent.com/16135252/106746326-481d6180-661a-11eb-8ada-c71ae71625f4.png)
MDT showing ! symbol this week:
Fortified
Inspiring
Storming
Prideful

**Steps to replicate**:
Open MDT in WoW
Go to Necrotic Wake dungeon map (could happen for more haven't fully tested)
Press New
Base the new map off Default.
Set the week to this weeks affixes

**Expected**: No ! symbol
**Actual**: ! symbol for wrong week showing, redirects to week 1

MDT:GetCurrentAffixWeek() seems to be returning the wrong value at this point, not sure if the call to C_MythicPlus.GetCurrentAffixes is returning wrong, or if the comparison to the MDT Affix table is incorrect:
for week,affixes in ipairs(affixWeeks) do
        if affixes[1] == affixIds[2].id and affixes[2] == affixIds[3].id and affixes[3] == affixIds[1].id then
            return week
        end
    end

could also be this retuning 1 
main_frame.sidePanel.affixDropdown:SetAffixWeek(MDT:GetCurrentPreset().week or (MDT:GetCurrentAffixWeek() or 1)) when the previous functions are erroring

**Impact**: Only a visual error to prompt the user to change the week, the rest of the addon functionality appears to work properly (ie on inspiring weeks the inspiring mobs are circled in yellow when the dropdown is set correctly) Leads me to believe its an issue in MDT:GetCurrentAffixWeek(). Perhaps the return values no longer line up wiht the affixWeeks array.
**Severity**: Low (4)
**Priority**: Low (4)

Happy to provide any more information. Don't expect this to be a priority at all but thought I would log it all the same

**Comment by Salmonwastaken** [comment]
Likely fixed by this pull request 
https://github.com/Nnoggie/MythicDungeonTools/pull/208

**Comment by Nnoggie** [comment]
fixed in v3.4.7
