### ISSUE TITLE
Incorrect NPCs linked to group in HoA

### ISSUE THREAD

**Issue by KalleZ** [Nnoggie/MythicDungeonTools#219]
It seems that the two Depraved Obliterators (Depraved Obliterator 5 & 6) in G 12 is incorrectly linked to the Shard of Halkias 1 and it's associated Depraved Collector 1:

![image](https://user-images.githubusercontent.com/147050/107140801-3d6e0f80-692d-11eb-901d-39108f65cb7a.png)

The same is true for the 2 other groups of Shard Halias:
![image](https://user-images.githubusercontent.com/147050/107140817-67bfcd00-692d-11eb-8456-7354187d2cb9.png)
![image](https://user-images.githubusercontent.com/147050/107140821-7908d980-692d-11eb-94bb-19dd3e8df0ad.png)

It is true however that the Shard of Halias is linked to the associated Depraved Collector in each group, but both of the Depraved Obliterators are separate.

**Comment by gende0808** [comment]
To add to this, the two Stoneborn Slashers at the stairs are also linked to each other.

**Comment by Nnoggie** [comment]
fixed
