### ISSUE TITLE
Blank Window when MDT is clicked

### ISSUE THREAD

**Issue by kumakajiya** [Nnoggie/MythicDungeonTools#223]
I haven't used Mythic Dungeon Tools in a long while, but now when I try to open it I just see a blank Window as seen in the image. I have uninstalled and reinstalled Mythic Dungeon Tools multiple times with no luck. I am also going to leave to what was picked up in bugsack and bugggrabber. I am not sure which of these may have the problem, but I am leaving screenshots of all of the errors that had Mythic Dungeon Tools included in them somewhere. 
![WoWMDTScreenshot](https://user-images.githubusercontent.com/80135560/110188823-08998f00-7deb-11eb-8934-c9e81af28f20.png)
 Screenshots:
[https://gyazo.com/e15eb0e4f8e49de42c69f7eeb9eeaa3d](url1)
[https://gyazo.com/640a4ae939bb4ff2ce0e03446c8bfb0c](url2)
[https://gyazo.com/ce4123460ddc5754d6378ef62f39dc9c](url3)
[https://gyazo.com/25cbe24112f755e571b0391b3203718f](url4)
[https://gyazo.com/766a695918302f9957708cf292cbad3b](url5)
[https://gyazo.com/a4318bcb6113140e077694d55cf16652](url6)
[https://gyazo.com/14cd037fc116ff55e33690654c0c535d](url7)

**Comment by MoultenWOW** [comment]
Same problem for me too !

**Comment by kumakajiya** [comment]
In the last update to Mythic Dungeon Tools, whatever was done fixed my Mythic Dungeon Tools and it is working now.

**Comment by MoultenWOW** [comment]
> In the last update to Mythic Dungeon Tools, whatever was done fixed my Mythic Dungeon Tools and it is working now.

didn't fix the problem for me :/

**Comment by Nnoggie** [comment]
If you have the AddOn "Jojo's Bizarre adventure SFX for Monk" enabled please disable it to be able to use MDT. That AddOn has an extremely out of date version of a library packaged which prevents other AddOns from working properly.
