### ISSUE TITLE
[Request] Option to hide the minimap button

### ISSUE THREAD

**Issue by akbyrd** [Nnoggie/MythicDungeonTools#227]
This may already exist, but for the life of me I can't find it.

**Comment by Nnoggie** [comment]
already exists in the interface options

**Comment by akbyrd** [comment]
Can you tell me how to find those options? When I click the minimap button or type `/mdt` I can' t seem to find any options. Google searching didn't help either.

**Comment by Nnoggie** [comment]
Interface Options

**Comment by akbyrd** [comment]
If anyone else comes across this, it's in the _Blizzard_ interface options. The options are not reachable from the MDT window in any way.

Esc > Interface > Addons > MythicDungeonTools
