### ISSUE TITLE
Black screen when trying to open MDT

### ISSUE THREAD

**Issue by Beurt460** [Nnoggie/MythicDungeonTools#232]
Hey ! 
I have a problem with Mythic Donjon Tools.
For a few days now, I can no longer launch it, it gives me a black screen with nothing happening 

![image](https://user-images.githubusercontent.com/81087173/111905329-5f3dd480-8a4b-11eb-94e0-79ab71da2741.png)

It's up to date, I even uninstall and reinstall it still get me this black screen

When i try to open it, I get this issue
[error.txt](https://github.com/Nnoggie/MythicDungeonTools/files/6177416/error.txt)

Thanks in advance for the help

**Comment by Nnoggie** [comment]
You seem to have another AddOn which is conflicting with MDT. Disable all other AddOns and enable each AddOn one by one accompanied with a /reload to figure out which AddOn is causing problems.

**Comment by Beurt460** [comment]
Ok I just found that it's an SFX addon that was causing problems with MDT. Guess my monk is not going to do jojo's noise anymore.
Thanks for your quick help !
keep going what you're doing, it's a great work! thanks !

**Comment by Nnoggie** [comment]
Could you link the AddOn that was causing problems?

**Comment by Beurt460** [comment]
Sure !
It was this one : https://www.curseforge.com/wow/addons/jojos-bizarre-adventure-sfx
