### ISSUE TITLE
Theater of Pain pack aggro incorrectly displayed

### ISSUE THREAD

**Issue by hampuswiden** [Nnoggie/MythicDungeonTools#234]
The following pack in Theater of Pain does not share aggro as is currently shown in MDT. The first 3 mobs (1 Battlefield Ritualist and 2 Unyielding Contenders) *do* share aggro as a pack (if you pull one you pull all of them) but they do *not* share aggro with the Raging Bloodhorn mob.

Please consider splitting these 4 mobs up into 2 packs as it is currently not possible to create a route in where you e.g only want to kill the Raging Bloodhorn. 
![mdt_top_chain_aggro](https://user-images.githubusercontent.com/36271659/113241389-e6424680-92ae-11eb-85fa-d2c9e6b64936.PNG)

**Comment by Nnoggie** [comment]
Use CTRL+Click to single select enemies.

**Comment by hampuswiden** [comment]
Had no idea this was a feature, thank you!
