### ISSUE TITLE
Route Overlays

### ISSUE THREAD

**Issue by LionHokies** [Nnoggie/MythicDungeonTools#244]
Improvement request - allow the ability to have an overlay to know which pull you are on and which mobs are in the pull.  This would reduce the amount of memorization needed for the entire route and reduce the need to have to open the main window during a mythic run.

**Comment by RShadowhand** [comment]
You can use MDTGuide addon for this. It's not 100% what you want, but it has auto-follow based on % reached.
However, and official solution OR integration of MDTGuide to MDT itself would be amazing!
