### ISSUE TITLE
attempt to call method 'SetBackdrop' (a nil value)

### ISSUE THREAD

**Issue by speedwaystar** [Nnoggie/MythicDungeonTools#251]
6x ...onTools\libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:377: attempt to call method 'SetBackdrop' (a nil value)
[string "@MythicDungeonTools\libs\LibUIDropDownMenu\LibUIDropDownMenu.lua"]:377: in function <...onTools\libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:367>
[string "@MythicDungeonTools\libs\LibUIDropDownMenu\LibUIDropDownMenu.lua"]:574: in function `create_DropDownButtons'
[string "@MythicDungeonTools\libs\LibUIDropDownMenu\LibUIDropDownMenu.lua"]:603: in main chunk

Locals:
name = "L_DropDownList1"
parent = nil
f = L_DropDownList1 {
 0 = <userdata>
}
fbd = L_DropDownList1Backdrop {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = L_DropDownList1Backdrop {
 0 = <userdata>
}
(*temporary) = <table> {
 bgFile = "DialogFrame\UI-DialogBox-Background-Dark"
 tileSize = 32
 edgeFile = "DialogFrame\UI-DialogBox-Border"
 tile = true
 edgeSize = 32
 insets = <table> {
 }
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
_G = <table> {
 ContainerFrame5Item7 = ContainerFrame5Item7 {
 }
 ARKINV_Frame1ScrollContainerBag5Item23ArkIconOverlay = ARKINV_Frame1ScrollContainerBag5Item23ArkIconOverlay {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 746
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 402
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 InterfaceOptionsNamesPanelUnitNameplatesShowAll = InterfaceOptionsNamesPanelUnitNameplatesShowAll {
 }
 LFGListInviteDialog_OnEvent = <function> defined @FrameXML\LFGList.lua:2495
 MerchantItem3AltCurrencyFrameItem1Text = MerchantItem3AltCurrencyFrameItem1Text {
 }
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 CHAT_HEADER_SUFFIX = ": "
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 COVENANT_MISSIONS_HEALTH = "Health"
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @FrameXML\UnitFrame.lua:789
 PaperDollTitlesPaneButton13BgTop = PaperDollTitlesPaneButton13BgTop {
 }
 ERR_NOAMMO_S = "%s"
 IAT_Achievement_2_140 = IAT_Achievement_2_140 {
 }
 MoneyFrame_OnEvent = <function> defined @FrameXML\MoneyFrame.lua:202
 AceConfigDialogTooltipTexture20 = AceConfigDialogTooltipTexture20 {
 }
 CinematicFrameRaidBossEmoteFrame = CinematicFrameRaidBossEmoteFrame {
 }
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LFGTeleport = <function> defined =[C]:-1
 LE_GAME_ERR_ONLY_ONE_QUIVER = 33
 SpellButton6Cooldown = SpellButton6Cooldown {
 }
 ToggleEncounterJournal = <function> defined @FrameXML\UIParent.lua:1057
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 Graphics_QualityText = Graphics_QualityText {
 }
 OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
 }
 FriendsFriendsScrollFrameButton14 = FriendsFriendsScrollFrameButton14 {
 }
 CompactUnitFrameProfilesSaveButton = CompactUnitFrameProfilesSaveButton {
 }
 RaidGraphics_EnvironmentalDetailSlider = RaidGraphics_EnvironmentalDetailSlider {
 }
 ARKINV_Frame4TitleActionButton2 = ARKINV_Frame4TitleActionButton2 {
 }
 Is64BitClient = <function> defined =[C]:-1
 CompactRaidFrameManagerDisplayFrameFilterOptionsFilterRoleTankMiddleMiddle = CompactRaidFrameManagerDisplayFrameFilterOptionsFilterRoleTankMiddleMiddle {
 }
 TutorialFrame_OnMouseDown = <function> defined @FrameXML\TutorialFrame.lua:376
 ContainerFrame4Item16Cooldown = ContainerFrame4Item16Cooldown {
 }
 LE_GAME_ERR_AZERITE_ESSENCE_SELECTION_FAILED_ESSENCE_NOT_UNLOCKED = 1021
 DUNGEON_FLOOR_DRAGONBLIGHTCHROMIESCENARIO2 = "Andorhal"
 PlayerFrame_UpdateReadyCheck = <function> defined @FrameXML\PlayerFrame.lua:460
 L = <table> {
 }
 WowTokenRedemptionFrameBg = WowTokenRedemptionFrameBg {
 }
 LFGListEntryCreation_GetAutoCreateData = <function> defined @FrameXML\LFGList.lua:969
 LAG_TOLERANCE = "Lag Tolerance"
 SendStationeryBackgroundRight = SendStationeryBackgroundRight {
 }
 HekiliDB = <table> {
 }
 PetStableStabledPet7 = PetStableStabledPet7 {
 }
 _ = "Horde"
 CONQUEST_BAR = "Conquest %d / %d"
 MultiBarLeftButton9Border = MultiBarLeftButton9Border {
 }
 LE_GAME_ERR_NOT_ON_TOURNAMENT_REALM = 838
 OPTION_TOOLTIP_SHOW_ACCOUNT_ACHIEVEMENTS = "

**Comment by Nnoggie** [comment]
Another AddOn is most likely conflicting. 
MDT has recently upgraded from a problamatic version to the newest version of a Library called "LibUIDropDownMenu" - other AddOns are also using this library. Please disable other AddOns one by one until you find which AddOn is causing the conflict.

**Comment by speedwaystar** [comment]
found it. thanks. it was a really old addon called JojoMonk.
