### ISSUE TITLE
 Affixes and weeks

### ISSUE THREAD

**Issue by ALPHASOSOCHKA** [Nnoggie/MythicDungeonTools#257]
Affixes and weeks are displayed incorrectly, I have question marks instead of two affixes, and MDT can't see the correct week. (addone updated recently ofc)
![image](https://user-images.githubusercontent.com/87594318/126057003-6df152e0-5a8d-42b2-98a6-595a73bc3aff.png)

**Comment by kdambay** [comment]
Same issue here, addon is updated but current week is displayed incorrectly. Has been like this since start of Season 2

**Comment by Pagefour** [comment]
Same issue here. Latest update.
