### ISSUE TITLE
Legion Dungeon Data not loading

### ISSUE THREAD

**Issue by Jodsderechte** [Nnoggie/MythicDungeonTools#265]
As i assume noone has used the legion part of this addon in a while noone reliased it's broken.
Trash mobs abilitys missing+boss completly missing. Guess it never got modernized with the namechange

Addon Version 3.7.0
GameVersion 9.1.5.sth

13x MythicDungeonTools\DungeonEnemies.lua:495: attempt to concatenate field '?' (a nil value)
[string "@MythicDungeonTools\DungeonEnemies.lua"]:495: in function `DisplayBlipTooltip'
[string "@MythicDungeonTools\DungeonEnemies.lua"]:96: in function <MythicDungeonTools\DungeonEnemies.lua:92>

Locals:
self = <table> {
 DeleteAllPresets = <function> defined @MythicDungeonTools\MythicDungeonTools.lua:3090
 DungeonEnemies_UpdateSelected = <function> defined @MythicDungeonTools\DungeonEnemies.lua:853
 GetCurrentPull = <function> defined @MythicDungeonTools\MythicDungeonTools.lua:2354
 LiveSession_RequestSession = <function> defined @MythicDungeonTools\LiveSession.lua:83
 PingMap = <function> defined @MythicDungeonTools\MythicDungeonTools.lua:2328
 AddPull = <function> defined @MythicDungeonTools\MythicDungeonTools.lua:4057
 DungeonEnemies_UpdateSeasonalAffix = <function> defined @MythicDungeonTools\DungeonEnemies.lua:961
 HideInterface = <function> defined @MythicDungeonTools\MythicDungeonTools.lua:682
 GetBlip = <function> defined @MythicDungeonTools\DungeonEnemies.lua:767
 RestoreScrollframeScripts = <function> defined @MythicDungeonTools\toolbar.lua:499
 GetFullScreenSizes = <function> defined @MythicDungeonTools\MythicDungeonTools.lua:868
 ADDON_LOADED = <function> defined @MythicDungeonTools\MythicDungeonTools.lua:146
 UpdateDungeonEnemies = <function> defined @MythicDungeonTools\MythicDungeonTools.lua:2650
 IsFrameOffScreen = <function> defined @MythicDungeonTools\MythicDungeonTools.lua:1010
 dungeonEnemies = <table> {
 }
 IsCurrentPresetTyrannical = <function> defined @MythicDungeonTools\MythicDungeonTools.lua:2289
 POI_CreateFramePools = <function> defined @MythicDungeonTools\Pointsofinterest.lua:9
 CreateDevPanel = <function> defined @MythicDungeonTools\devpanel.lua:134
 StartEraserDrawing = <function> defined @MythicDungeonTools\toolbar.lua:842
 SetLivePreset = <function> defined @MythicDungeonTools\MythicDungeonTools.lua:2424
 GetDungeonName = <function> defined @MythicDungeonTools\MythicDungeonTools.lua:277
 LiveSession_SendPreset = <function> defined @MythicDungeonTools\LiveSession.lua:201
 UpdateEnemyInfoData = <function> defined @MythicDungeonTools\EnemyInfo.lua:585
 HardReset = <function> defined @MythicDungeonTools\MythicDungeonTools.lua:4973
 CleanEnemyData = <function> defined @MythicDungeonTools\DungeonEnemies.lua:1348
 GetHighestFrameLevelAtCursor = <function> defined @MythicDungeonTools\toolbar.lua:530
 DisplayBlipTooltip = <function> defined @MythicDungeonTools\DungeonEnemies.lua:460
 ClearPull = <function> defined @MythicDungeonTools\MythicDungeonTools.lua:4094
 StringToTable = <function> defined @MythicDungeonTools\Transmission.lua:92
 SkinProgressBar = <function> defined @MythicDungeonTools\MythicDungeonTools.lua:983
 MakeRenameFrame = <function> defined @MythicDungeonTools\MythicDungeonTools.lua:4171
 DungeonEnemies_UpdateBoralusFaction = <function> defined @MythicDungeonTools\DungeonEnemies.lua:1010
 initToolbar = <function> defined @MythicDungeonTools\toolbar.lua:15
 POI_UpdateAll = <function> defined @MythicDungeonTools\Pointsofinterest.lua:486
 OpenCustomColorsDialog = <function> defined @MythicDungeonTools\MythicDungeonTools.lua:2722
 LiveSession_SendCommand = <function> defined @MythicDungeonTools\LiveSession.lua:180
 MakeCustomColorFrame = <function> defined @MythicDungeonTools\MythicDungeonTools.lua:3586
 UpdatePresetDropDown = <function> defined @MythicDungeonTools\MythicDungeonTools.lua:1895
 HSVtoRGB = <function> defined @MythicDungeonTools\MythicDungeonTools.lua:4538
 RequestDataCollectionUpdate = <function> defined @MythicDungeonTools\DataCollection.lua:230
 poi_framePools = <table> {
 }
 MakePresetImportFrame = <function> defined

**Comment by Nnoggie** [comment]
Fixed in 03f1bd14cfd7ae58684ca6879080b61540ee0c96 and 6659ec5993aefdbb76c3e18f1539d4199114033a.
Thanks for the report!
The next release version of the AddOn will incorporate these changes.
