### ISSUE TITLE
Spires has multiple packs showing every mob as Inspired

### ISSUE THREAD

**Issue by Saxayone** [Nnoggie/MythicDungeonTools#267]
Spires has multiple packs showing every mob as Inspired with 3.7.2
![Screenshot 2021-11-25 182344](https://user-images.githubusercontent.com/47307427/143487792-27c3ab7e-474b-4a14-a3fe-df461173ce91.png)

**Comment by Nnoggie** [comment]
fixed in 3acb90544783937c4ee05a6823528eb2ba540063
