### ISSUE TITLE
Patrol-path Tazavezh is not found

### ISSUE THREAD

**Issue by amarques** [Nnoggie/MythicDungeonTools#279]
Hello,

Sorry to bother u dev team, u are planning put the patrol-path of Tazavezh dungeons up?
I'm know some dung like Gambit beach or Streets can be a bit annoying but will be really useful to plan strategy.

Thanks a lot and kind regards

**Comment by Nnoggie** [comment]
Patrol paths implemented in 87e1150336a8ae63c06811ad579404149571a4e8
