### ISSUE TITLE
Tazavesh: Fortified and Tyrannical mob health are reversed

### ISSUE THREAD

**Issue by mechiah** [Nnoggie/MythicDungeonTools#285]
On Streets of Wonder and Soleah's Gambit maps, mob health is shown higher on tyrannical weeks, and boss health higher on fortified weeks.

I spot checked against MotS, which does not have this issue. 

I haven't verified if any of the health values are correct.

**Comment by mechiah** [comment]
FWIW my guildie confirmed on his client as well. Updated to latest via Curse app before posting.

**Comment by Nnoggie** [comment]
fixed in v3.8.7
