### ISSUE TITLE
attempt to indox local button

### ISSUE THREAD

**Issue by Jodsderechte** [Nnoggie/MythicDungeonTools#291]
game verison 9.2.sthsth
mdt version 3.9.1

1x ...aceMythicDungeonTools\MythicDungeonTools-3.9.1.lua:4467: attempt to index local 'button' (a nil value)
[string "@MythicDungeonTools\MythicDungeonTools-3.9.1.lua"]:4467: in function `UpdatePullButtonColor'
[string "@MythicDungeonTools\MythicDungeonTools-3.9.1.lua"]:3072: in function `ColorPull'
[string "@MythicDungeonTools\MythicDungeonTools-3.9.1.lua"]:2509: in function `UpdateToDungeon'
[string "@MythicDungeonTools\MythicDungeonTools-3.9.1.lua"]:2861: in function `ImportPreset'
[string "@MythicDungeonTools\MythicDungeonTools-3.9.1.lua"]:2705: in function <...aceMythicDungeonTools\MythicDungeonTools.lua:2701>
[string "=[C]"]: ?
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Ace3\AceGUI-3.0-41\widgets\AceGUIWidget-Button.lua"]:22: in function <...dOns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:19>

**Comment by Nnoggie** [comment]
Please provide your MythicDungeonTools.lua from C:\Program Files (x86)\World of Warcraft_retail_\WTF\Account<accountname>\SavedVariables

**Comment by Jodsderechte** [comment]
[MythicDungeonTools.zip](https://github.com/Nnoggie/MythicDungeonTools/files/8592233/MythicDungeonTools.zip)

**Comment by Nnoggie** [comment]
How does this error happen? Are you trying to import a certain route? Could not reproduce the error with the provided saved variables.

**Comment by Jodsderechte** [comment]
tbh i've only seen this error happen once so far so i can't rly tell you the reproduction steps just wanted to let you know incase its sth easy. However i'll keep an eye out when it happens again
