### ISSUE TITLE
Street of Wonder: A Interrogation Specialist Should Be Replaced by a Support Officer

### ISSUE THREAD

**Issue by FlareStarrr** [Nnoggie/MythicDungeonTools#296]
Street of Wonder: a Interrogation Specialist should be replaced by a Support Officer. Thank you.
![Interrogation Specialist replaced by Support Officer](https://user-images.githubusercontent.com/32023701/166860456-85959bde-8ef9-48d5-b9fb-e013f60e1ac6.png)
![Interrogation Specialist replaced by Support Officer 2](https://user-images.githubusercontent.com/32023701/166860466-2d2b9dcf-8e70-43d0-841d-5f40b7842b33.png)

**Comment by Nnoggie** [comment]
Nice catch!
