### ISSUE TITLE
De Other Side total count is off

### ISSUE THREAD

**Issue by ljosberinn** [Nnoggie/MythicDungeonTools#300]
just posting so I don't forget to report it so sorry for the lack of detail.

latest version introduced a regression in DOS, requiring more count than actually needed (or some mobs not being counted anymore). routes that are technically 100% or above show up as 97%.

**Comment by Nnoggie** [comment]
This might have to do with the npc id of Atal'ai Devoted changing. Refer to https://github.com/Nnoggie/MythicDungeonTools/commit/ad2d16d7730f6eeefbbbecf84180e2ac562e4b2f

**Comment by ljosberinn** [comment]
ah perfect, I'm too late :)
