### ISSUE TITLE
Windows Defender Detecting Trojan

### ISSUE THREAD

**Issue by tehpieguy514** [Nnoggie/MythicDungeonTools#343]
I saw some closed issues in 2021 about this, but just wanted to bring to your attention that the latest version of Windows Defender is flagging a trojan in the version of MDT I am using. Probably a false positive, but just wanted to be sure.

This is for the zip file I downloaded directly from CurseForge.

![image](https://user-images.githubusercontent.com/110949424/183788674-689765c2-35c3-4348-9e9d-b98236ff980c.png)

**Comment by Nnoggie** [comment]
Did you download this version from curseforge? The latest version on curseforge is v3.9.5.7 which you can find here https://www.curseforge.com/wow/addons/mythic-dungeon-tools.

Thank you for the report, i will forward this to curseforge. For your peace of mind: MDT (infact any AddOn) does not execute any code on your machine by itself. All it does is provide lua code for World of Warcraft which then interprets the lua code and runs it in it's own Sandbox.

**Comment by tehpieguy514** [comment]
That's what I figured. Thanks Nnoggie! Appreciate the work you do on this :)

**Comment by Nnoggie** [comment]
leaving this open until curseforge/microsoft has resolved the issue

**Comment by Nnoggie** [comment]
closing this, as i have not hear more about this issue. seems to be resolved!
