### ISSUE TITLE
Miss mob spells

### ISSUE THREAD

**Issue by HildoYe** [Nnoggie/MythicDungeonTools#344]
There are tons of mobs have spells but are not listed in the MDT right click UI especially the old dungeons. Despite there are some spells are not in the wowhead database, there are still some spells existed in the database but not in MDT. 
Simple example: Spectral Valet in lower karazhan can cast Demoralizing Shout but there is no such spell in MDT.

**Comment by Nnoggie** [comment]
Spells, characteristics and health updates are currently incomplete.
Will update in the next weeks
![image](https://user-images.githubusercontent.com/27819512/184493979-f4a621f6-f27c-4222-80a2-a2111ef83fe2.png)
