### ISSUE TITLE
Error in low keys

### ISSUE THREAD

**Issue by shighman** [Nnoggie/MythicDungeonTools#345]
While valor farming in low keys <10 get the following error:
Message: ...ace\AddOns\MythicDungeonTools\MythicDungeonTools.lua:1901: attempt to index local 'clone' (a nil value)

**Comment by Nnoggie** [comment]
What version of MDT were you running?
Could you show the full Error Message and if possible export the Route where this error happens and paste the import string here!

**Comment by shighman** [comment]
Sorry i manually fixed it while i was grinding keys, but i updated today and reverted my changes and it seems to have been resolved.

Thanks for all your hard work :)
