### ISSUE TITLE
2 errors whet start mythic +

### ISSUE THREAD

**Issue by Mithras2801** [Nnoggie/MythicDungeonTools#364]
First:

Message: Lua error in aura 'Pull Number': Custom Text Function
WeakAuras Version: 4.1.4
Aura Version: 1.0.16
...ace\AddOns\MythicDungeonTools\MythicDungeonTools-3.9.6.9.lua:1914: attempt to index local 'clone' (a nil value)
Time: Sat Sep 24 14:03:15 2022
Count: 674
Stack: Lua error in aura 'Pull Number': Custom Text Function
WeakAuras Version: 4.1.4
Aura Version: 1.0.16
...ace\AddOns\MythicDungeonTools\MythicDungeonTools-3.9.6.9.lua:1914: attempt to index local 'clone' (a nil value)

Locals: <none>

2nd error:

Message: Lua error in aura 'Pull Number': Custom Action
WeakAuras Version: 4.1.4
Aura Version: 1.0.16
...ace\AddOns\MythicDungeonTools\MythicDungeonTools-3.9.6.9.lua:1914: attempt to index local 'clone' (a nil value)
Time: Sat Sep 24 13:48:36 2022
Count: 1
Stack: Lua error in aura 'Pull Number': Custom Action
WeakAuras Version: 4.1.4
Aura Version: 1.0.16
...ace\AddOns\MythicDungeonTools\MythicDungeonTools-3.9.6.9.lua:1914: attempt to index local 'clone' (a nil value)

Locals: <none>

**Comment by Nnoggie** [comment]
This is a lua error in the WeakAura 'Pull Number', not in MDT.
