### ISSUE TITLE
Hotkey

### ISSUE THREAD

**Issue by WarauNikx** [Nnoggie/MythicDungeonTools#378]
Seems maybe addon is not registering itself anymore to provide keybind management, 
Believe previously could go into keybinds and find mdt and set to open with certain keypress and am not seeing that option presented anymore.

**Comment by Nnoggie** [comment]
This is indeed intended. Adding keybinds from AddOns could taint the user interface. This is a bug on blizzard's side and until it is fully fixed keybinds will remain missing from MDT. You can still make macros and call the functions via lua scripts though! Here are the macros for the bindings that were removed: 

/run MDT:PresetObjectStepBack(); 

/run MDT:PresetObjectStepForward();  

/run MDT:ShowInterface();
