### ISSUE TITLE
Temple of the Jade Serpent

### ISSUE THREAD

**Issue by KhubiTv** [Nnoggie/MythicDungeonTools#405]
Hello,

If I use your addon and look at the temple, I realize that I can't get to 100%. I selected all bosses and mobs and then only complete 85.6% overall. Am I doing something wrong or are there any mob groups missing?

**Comment by Wotuu** [comment]
I noticed this as well (a few days ago) but the entire second floor is missing. This will need to be added and then life will be good again.

**Comment by KhubiTv** [comment]
Nice ;) before the final boss, the 5 adds are also missing on the map. You can see the sha but not the adds.

**Comment by Wotuu** [comment]
Yeah so I just took a look at it and the 2nd floor is technically missing, but it was opted to merge the 2nd floor into the 1st floor, hence my confusion. Following a recorded video the issue seems to be the last packs that are added to the dungeon and that's it.
