### ISSUE TITLE
MDT Loads blank maps with no options / blank window and then cannot be closed.

### ISSUE THREAD

**Issue by KallahSmith** [Nnoggie/MythicDungeonTools#412]
Hey. Getting into tanking keys so want to get my routes down. I downloaded Mythic Dungeon Tool (v. 4.0.1.21) and when I try to open it in game I get all the empty maps but no options with them or just a blank window (see image below). It is the same response after I disable all other addons.

Do you have any idea what I need to do in order to fix? Thanks in advance!

![MDT Bug](https://user-images.githubusercontent.com/121686292/210095468-8683e31d-7929-40a1-b391-75df0379bdff.png)

**Comment by KallahSmith** [comment]
Message: Interface/AddOns/DungeonTools/DungeonEnemies.xml:74 Unrecognized XML attribute: textureSubLevel
Time: Sat Dec 31 15:51:44 2022
Count: 1

**Comment by Nnoggie** [comment]
please report all errors relating to mdt when opening the addon ingame
