### ISSUE TITLE
SBG: Missing mobs in Group 25

### ISSUE THREAD

**Issue by Bukama** [Nnoggie/MythicDungeonTools#424]
What we all know is that you can pull Group 25 in SBG before Bonemaw (3rd Boss, worm boss) by e.g. gliding around the barrier as an DH or Evoker. 

Watching this weekend MDI I realized that this is not only a possibility to get the mobs to cleave with one of the worm adds or the boss, but that there are small spiders in the group you kill for extra count. But these small spiders disappear when you kill the boss, before pulling G25.

About the count.
I rebuild the route of TeamSWE rebuilding every pull when they are at the boss
```
!LrvtZXjmm0)sy8hahBAo00dUzg2Ph9KLfrcTSqgWKKEj)2RLK5JLmzcSy)KEsp9SDc3jx5566H(FdJtTd9oRkjv5kVm0nm(45oW7Hh6BgiCZ(HVJR32)S7UdyQ)ieQZ7k9WhHNNGZx)8PP3HpFAeQMB7QDL1TnnTxM78)ZzfjUY3b4V8VMBdBF)R5D3z7F4hYV5kF7C3mGKEzECe69po31XyJluox1bVbHftDLtqhCXJL)PaicNFf59Z9pdd9CfAWceUIDqLRCSTX)RMMjWprrMeE6XqFnqhV0Uh2mKmRXzLoBEaw4lEdj(HIc2Q5xMLTsPGKekRuI4SsfIZk1C2muQLzywTYW)fHxfu9eghH3m3covcIDRqr4eAgNGllrgla5epIcIN0eKhpMKO(GFKtfkpfDLnnsOPzvdcPMLcUhn8IbQpTekNhBS9IAGincuTLLdOiYxyf5SaqKscP4ybIFyOGZO8M8LIwcB0SmG8lZJ1COOD0R5GNA4AQ915gSTkSa1L4GDJ4MkKyH8GsSObRnXIpqXiuSmOyFGI9bk2hOyFGkNMVQcA(QtOk2QfK8y1Pedwvg3LMDvfQMyvTWPj2ofeNMeItJG40WozJM40yionS3Ze9EzlEpbZPjJ6yRrstyRgFhsGgTAHmOrVyaJo8B0bQr8ypKFJUS3mOzDG7f2EQ2lFRcSE3zp5Aq7ncSpk)GEqEA1kZ(LP9wKf3ojZ352s)IdCX)Srr8ydFS37IE4dhyK3yBpl45u80c)x516wmXnJa8Yqx9phA7HA8wQk45WfO4vwHAzDFwGkhQ(t4QVPyIC))d
```

![teamsweMDT](https://user-images.githubusercontent.com/4354359/220043462-ddaeea71-461a-4552-91a0-aecf49930ab8.png)

As you can see the count is 90.00% in the route. But when you look at the actual count in game its 93.33. So 3.33% extra count by spiderlings.

![teamswe](https://user-images.githubusercontent.com/4354359/220042640-083b491a-79e6-4648-bb67-214a042193df.png)

As a verification here's another screenshot from their count before pulling the spiderpack / while fighting the single worm. If you compare it with the route you see that I didn't miss anything as without the worm the route is at 77.67%

![lastworm](https://user-images.githubusercontent.com/4354359/220042976-eb412677-127d-443e-98bc-a4eed5b58b55.png)

I'm not very creative how to add this to MDT in terms of visualize it and show that this count is only available when you do the special pull, but I think it should be included as many groups play the pull and the extra 3,33% count allows you to skip other pulls.

**Comment by Nnoggie** [comment]
fixed
