### ISSUE TITLE
MDT sometimes bugging out

### ISSUE THREAD

**Issue by atasi90** [Nnoggie/MythicDungeonTools#426]
Hello everyone, around the time of the last update I have the issue that MDT sometimes bugs out for me if I open it during combat and/or randomly even when not in combat. What happens is that I can only see the borders of the main window but the map/all mobs/everything else expect the border is not loading. Sometimes it comeplety crashes for me and I can't close the window anymore.

I don't have any screenshots atm, but can add them next time it happens for me.

The bug fixes itself with a /reload. I didn't have that issue ever before and I've already tried to re-install the addon via the client (but maybe not all files where correctly deleted and re-installed).

I guess I have some corrupted files somewhere, but maybe anyone here has an idea how to fix this problem. 

Thanks very much 

edit: here are some error messages that got stored:

```
1x ...aceMythicDungeonTools/MythicDungeonTools.lua:4828: script ran too long
[string "@MythicDungeonTools/MythicDungeonTools.lua"]:4828: in function <...aceMythicDungeonTools/MythicDungeonTools.lua:4618>
[string "@MythicDungeonTools/MythicDungeonTools.lua"]:382: in function `ShowInterface'
[string "@MythicDungeonTools/MythicDungeonTools.lua"]:52: in function `OnClick'
[string "@BugSack/Libs/LibDBIcon-1.0-45/LibDBIcon-1.0.lua"]:144: in function <BugSack/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:142>

Locals:
Skipped (In Encounter)
```

```
5x ...aceMythicDungeonTools/MythicDungeonTools.lua:404: attempt to index field 'HelpButton' (a nil value)
[string "@MythicDungeonTools/MythicDungeonTools.lua"]:404: in function `HideInterface'
[string "@MythicDungeonTools/MythicDungeonTools.lua"]:418: in function <...aceMythicDungeonTools/MythicDungeonTools.lua:418>

Locals:
Skipped (In Encounter)
```

```
1x ...aceMythicDungeonTools/MythicDungeonTools.lua:4580: attempt to index field 'newPullButtons' (a nil value)
[string "@MythicDungeonTools/MythicDungeonTools.lua"]:4580: in function `GetPullButton'
[string "@MythicDungeonTools/MythicDungeonTools.lua"]:4584: in function `UpdatePullButtonColor'
[string "@MythicDungeonTools/MythicDungeonTools.lua"]:3211: in function `ColorPull'
[string "@MythicDungeonTools/MythicDungeonTools.lua"]:2635: in function `UpdateToDungeon'
[string "@MythicDungeonTools/MythicDungeonTools.lua"]:2117: in function `ReturnToLivePreset'
[string "@MythicDungeonTools/MythicDungeonTools.lua"]:442: in function <...aceMythicDungeonTools/MythicDungeonTools.lua:442>

Locals:
self = <table> {
 DeleteAllPresets = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:2734
 DungeonEnemies_UpdateSelected = <function> defined @MythicDungeonTools/Modules/DungeonEnemies.lua:976
 dungeonSubLevels = <table> {
 }
 modules = <table> {
 }
 LiveSession_RequestSession = <function> defined @MythicDungeonTools/Modules/LiveSession.lua:83
 GetDungeonSublevels = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:364
 AddPull = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:3769
 DungeonEnemies_UpdateSeasonalAffix = <function> defined @MythicDungeonTools/Modules/DungeonEnemies.lua:1083
 HideInterface = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:402
 GetBlip = <function> defined @MythicDungeonTools/Modules/DungeonEnemies.lua:890
 dungeonSelectionToIndex = <table> {
 }
 RestoreScrollframeScripts = <function> defined @MythicDungeonTools/Modules/Toolbar.lua:503
 RegisterModule = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:4614
 ADDON_LOADED = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:179
 UpdateDungeonEnemies = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:2350
 IsFrameOffScreen = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:618
 dungeonEnemies = <table> {
 }
 IsCurrentPresetTyrannical = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:1991
 POI_CreateFramePools = <function> defined @MythicDungeonTools/Modules/Pointsofinterest.lua:8
 CreateDevPanel = <function> defined @MythicDungeonTools/Developer/Devpanel.lua:143
 StartEraserDrawing = <function> defined @MythicDungeonTools/Modules/Toolbar.lua:856
 SetLivePreset = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:2123
 GetDungeonName = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:362
 LiveSession_SendPreset = <function> defined @MythicDungeonTools/Modules/LiveSession.lua:204
 UpdateEnemyInfoData = <function> defined @MythicDungeonTools/Modules/EnemyInfo.lua:614
 CopyPullOptions = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:4562
 CleanEnemyData = <function> defined @MythicDungeonTools/Modules/DungeonEnemies.lua:1449
 GetHighestFrameLevelAtCursor = <function> defined @MythicDungeonTools/Modules/Toolbar.lua:534
 DisplayBlipTooltip = <function> defined @MythicDungeonTools/Modules/DungeonEnemies.lua:475
 ClearPull = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:3806
 StringToTable = <function> defined @MythicDungeonTools/Modules/Transmission.lua:92
 SkinProgressBar = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:591
 MakeRenameFrame = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:3881
 DungeonEnemies_UpdateBoralusFaction = <function> defined @MythicDungeonTools/Modules/DungeonEnemies.lua:1153
 initToolbar = <function> defined @MythicDungeonTools/Modules/Toolbar.lua:16
 POI_UpdateAll = <function> defined @MythicDungeonTools/Modules/Pointsofinterest.lua:663
 OpenCustomColorsDialog = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:2422
 LiveSession_SendCommand = <function> defined @MythicDungeonTools/Modules/LiveSession.lua:182
 MakeCustomColorFrame = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:3229
 UpdatePresetDropDown = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:1514
 HSVtoRGB = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:4167
 RequestDataCollectionUpdate =
```

**Comment by shrekin** [comment]
I had the same issue. Sometimes I open by mistake during combat and cannot close it. Only /reload helps. During combat is very annoying bug.

**Comment by Enkaf** [comment]
Got same issue.

![image](https://user-images.githubusercontent.com/28902145/224277073-235ebf21-b38f-4e66-bbec-5fc543e1c542.png)

**Comment by ljosberinn** [comment]
![image](https://user-images.githubusercontent.com/29307652/224400055-2be2b38b-f271-4707-b612-c16f4081648a.png)
same here, same  `script ran too long` error

only has been happening very recently, like, last 2 weeks, which is odd because there hasn't been a release so might be something on blizzards end

**Comment by ljosberinn** [comment]
commenting separately because this isnt an error from me, but it leads to the same visual bug:

> Message: Interface/SharedXML/Pools.lua:318: assertion failed!
> Time: Fri Mar 10 12:51:47 2023
> Count: 1
> Stack: Interface/SharedXML/Pools.lua:318: assertion failed!
> [string "@Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua"]:151: in function <...dOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:149>
> [string "=[C]"]: ?
> [string "=[C]"]: in function `assert'
> [string "@Interface/SharedXML/Pools.lua"]:318: in function `CreatePool'
> [string "@Interface/AddOns/MythicDungeonTools/Modules/DungeonEnemies.lua"]:872: in function `DungeonEnemies_CreateFramePools'
> [string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:4678: in function <...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:4618>
> [string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:4475: in function `ResetMainFramePos'
> [string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:4846: in function <...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:4618>
> [string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:382: in function `ShowInterface'
> [string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:95: in function `?'
> [string "@Interface/FrameXML/ChatFrame.lua"]:5229: in function `ChatEdit_ParseText'
> [string "@Interface/FrameXML/ChatFrame.lua"]:4893: in function `ChatEdit_SendText'
> [string "@Interface/FrameXML/ChatFrame.lua"]:4929: in function <Interface/FrameXML/ChatFrame.lua:4925>
> [string "=[C]"]: in function `ChatEdit_OnEnterPressed'
> [string "*ChatFrame.xml:127_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:127_OnEnterPressed"]:1>
> 
> Locals: private = <table> {
>  ThrowError = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:50
>  DoesErrorExist = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:92
>  ClearOldErrors = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:112
>  SanitizeLine = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:88
>  MAX_STACK_DEPTH = 10
>  log = <table> {
>  }
>  ErrorHandler = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:121
>  IncrementErrorCount = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:82
>  NewError = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:54
>  IsRCLootCouncilError = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:99
> }
> orig_errorhandler = <function> defined @Interface/SharedXML/SharedBasicControls.lua:360

**Comment by ljosberinn** [comment]
also relevant: https://discord.com/channels/327414731654692866/327414731654692866/1077393999494656080

**Comment by Nnoggie** [comment]
> also relevant: https://discord.com/channels/327414731654692866/327414731654692866/1077393999494656080

no access to this message!

**Comment by ljosberinn** [comment]
ah sorry thought you were in there too:
![image](https://user-images.githubusercontent.com/29307652/224713752-59c4b944-c59e-4795-a2d0-edc7af157784.png)

**Comment by ljosberinn** [comment]
sadly still persists, had it yesterday, manifesting with the same exact error as in https://github.com/Nnoggie/MythicDungeonTools/issues/426#issuecomment-1464240718 but sadly didn't catch the error as it was mid key and I had to instantly reload. will update when I have a stack trace
