### ISSUE TITLE
[MDT 4.0.2.5] MythicDungeonTools.lua:2058: attempt to index field 'ping' (a nil value)

### ISSUE THREAD

**Issue by Hollicsh** [Nnoggie/MythicDungeonTools#427]
8x ...aceMythicDungeonTools/MythicDungeonTools.lua:2058: attempt to index field 'ping' (a nil value)
[string "@MythicDungeonTools/MythicDungeonTools.lua"]:2058: in function `SetPingOffsets'
[string "@MythicDungeonTools/MythicDungeonTools.lua"]:1757: in function `ZoomMap'
[string "@MythicDungeonTools/MythicDungeonTools.lua"]:2207: in function <...aceMythicDungeonTools/MythicDungeonTools.lua:2188>

Locals:
self = <table> {
 DeleteAllPresets = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:2738
 DungeonEnemies_UpdateSelected = <function> defined @MythicDungeonTools/Modules/DungeonEnemies.lua:976
 dungeonSubLevels = <table> {
 }
 modules = <table> {
 }
 LiveSession_RequestSession = <function> defined @MythicDungeonTools/Modules/LiveSession.lua:83
 GetDungeonSublevels = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:369
 AddPull = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:3776
 DungeonEnemies_UpdateSeasonalAffix = <function> defined @MythicDungeonTools/Modules/DungeonEnemies.lua:1083
 HideInterface = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:407
 GetBlip = <function> defined @MythicDungeonTools/Modules/DungeonEnemies.lua:890
 dungeonSelectionToIndex = <table> {
 }
 RestoreScrollframeScripts = <function> defined @MythicDungeonTools/Modules/Toolbar.lua:503
 RegisterModule = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:4623
 ADDON_LOADED = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:180
 UpdateDungeonEnemies = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:2354
 IsFrameOffScreen = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:623
 dungeonEnemies = <table> {
 }
 IsCurrentPresetTyrannical = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:2000
 POI_CreateFramePools = <function> defined @MythicDungeonTools/Modules/Pointsofinterest.lua:8
 CreateDevPanel = <function> defined @MythicDungeonTools/Developer/Devpanel.lua:143
 StartEraserDrawing = <function> defined @MythicDungeonTools/Modules/Toolbar.lua:856
 SetLivePreset = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:2132
 GetDungeonName = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:367
 LiveSession_SendPreset = <function> defined @MythicDungeonTools/Modules/LiveSession.lua:204
 UpdateEnemyInfoData = <function> defined @MythicDungeonTools/Modules/EnemyInfo.lua:614
 CopyPullOptions = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:4571
 CleanEnemyData = <function> defined @MythicDungeonTools/Modules/DungeonEnemies.lua:1449
 GetHighestFrameLevelAtCursor = <function> defined @MythicDungeonTools/Modules/Toolbar.lua:534
 DisplayBlipTooltip = <function> defined @MythicDungeonTools/Modules/DungeonEnemies.lua:475
 ClearPull = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:3813
 StringToTable = <function> defined @MythicDungeonTools/Modules/Transmission.lua:92
 SkinProgressBar = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:596
 MakeRenameFrame = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:3888
 DungeonEnemies_UpdateBoralusFaction = <function> defined @MythicDungeonTools/Modules/DungeonEnemies.lua:1153
 initToolbar = <function> defined @MythicDungeonTools/Modules/Toolbar.lua:16
 POI_UpdateAll = <function> defined @MythicDungeonTools/Modules/Pointsofinterest.lua:663
 OpenCustomColorsDialog = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:2426
 LiveSession_SendCommand = <function> defined @MythicDungeonTools/Modules/LiveSession.lua:182
 MakeCustomColorFrame = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:3235
 UpdatePresetDropDown = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:1526
 HSVtoRGB = <function> defined @MythicDungeonTools/MythicDungeonTools.lua:4175
 RequestDataCollectionUpdate =

**Comment by Nnoggie** [comment]
fixed
