### ISSUE TITLE
MRT/ExLib.lua:3177: script ran too long

### ISSUE THREAD

**Issue by Hollicsh** [Nnoggie/MythicDungeonTools#431]
1x MRT/ExLib.lua:3177: script ran too long
[string "@MRT/ExLib.lua"]:3177: in function `Icon'
[string "@MRT/RaidCheck.lua"]:1900: in function <MRT/RaidCheck.lua:1899>
[string "@MRT/RaidCheck.lua"]:1940: in function <MRT/RaidCheck.lua:1920>
[string "@MRT/RaidCheck.lua"]:2011: in function `Create'
[string "@MRT/RaidCheck.lua"]:2855: in function `ReadyCheckWindow'
[string "@MRT/RaidCheck.lua"]:3075: in function <MRT/RaidCheck.lua:3065>
[string "=(tail call)"]: ?

Locals:
self = <table> {
 Shadow = <function> defined @MRT/ExLib.lua:1585
 CreateScrollCheckList = <function> defined @MRT/ExLib.lua:3988
 CreateCheckBox = <function> defined @MRT/ExLib.lua:3280
 CreateSliderBox = <function> defined @MRT/ExLib.lua:3065
 DebugBack = <function> defined @MRT/ExLib.lua:3357
 ModObjFuncs = <function> defined @MRT/ExLib.lua:257
 CreateScrollBarModern = <function> defined @MRT/ExLib.lua:2073
 EditBoxOnEnterHyperLinkTooltip = <function> defined @MRT/ExLib.lua:2264
 AddShadowComment = <function> defined @MRT/ExLib.lua:1477
 SliderBox = <function> defined @MRT/ExLib.lua:3034
 ScrollBar = <function> defined @MRT/ExLib.lua:1998
 Frame = <function> defined @MRT/ExLib.lua:5917
 CreateHoverHighlight = <function> defined @MRT/ExLib.lua:3343
 TooltipHide = <function> defined @MRT/ExLib.lua:2249
 DropDownButton = <function> defined @MRT/ExLib.lua:4263
 CreateScrollBar = <function> defined @MRT/ExLib.lua:2076
 HideAdditionalTooltips = <function> defined @MRT/ExLib.lua:2246
 CreateSlider = <function> defined @MRT/ExLib.lua:1821
 Button = <function> defined @MRT/ExLib.lua:3127
 Icon = <function> defined @MRT/ExLib.lua:3171
 Edit = <function> defined @MRT/ExLib.lua:2793
 CreateEditBox = <function> defined @MRT/ExLib.lua:2839
 Popup = <function> defined @MRT/ExLib.lua:4024
 DropDown = <function> defined @MRT/ExLib.lua:4222
 CreateText = <function> defined @MRT/ExLib.lua:2666
 DropDownClose = <function> defined @MRT/ExLib.lua:4745
 CreateShadow = <function> defined @MRT/ExLib.lua:1596
 ScrollList = <function> defined @MRT/ExLib.lua:3959
 Border = <function> defined @MRT/ExLib.lua:5937
 MultiEdit2 = <function> defined @MRT/ExLib.lua:5886
 ScrollButtonsList = <function> defined @MRT/ExLib.lua:6626
 CreateButton = <function> defined @MRT/ExLib.lua:3148
 ScrollTabsFrame = <function> defined @MRT/ExLib.lua:4115
 Texture = <function> defined @MRT/ExLib.lua:1557
 DecorationLine = <function> defined @MRT/ExLib.lua:6219
 Radio = <function> defined @MRT/ExLib.lua:3321
 TooltipShow = <function> defined @MRT/ExLib.lua:2273
 GraphCol = <function> defined @MRT/ExLib.lua:6182
 CreateScrollDropDown = <function> defined @MRT/ExLib.lua:4259
 Text = <function> defined @MRT/ExLib.lua:2628
 OnLeaveHyperLinkTooltip = <function> defined @MRT/ExLib.lua:2252
 MultiEdit = <function> defined @MRT/ExLib.lua:5837
 EditBoxOnClickHyperLinkTooltip = <function> defined @MRT/ExLib.lua:2267
 Tabs = <function> defined @MRT/ExLib.lua:2497
 CreateGraph = <function> defined @MRT/ExLib.lua:5478
 OnLeaveTooltip = <function> defined @MRT/ExLib.lua:2258
 CreateScrollTabsFrame = <function> defined @MRT/ExLib.lua:4143
 ListButton = <function> defined @MRT/ExLib.lua:4778
 AdditionalTooltip = <function> defined @MRT/ExLib.lua:2243
 CreateIcon = <function> defined @MRT/ExLib.lua:3189
 CreateScrollDropDownButton = <function> defined @MRT/ExLib.lua:4277
 CreateRadioButton = <function> defined @MRT/ExLib.lua:3338
 ScrollTableList = <function> defined @MRT/ExLib.lua:3965
 ScrollCheckList = <function> defined @MRT/ExLib.lua:3975
 FixPreloadFont = <function> defined @MRT/ExLib.lua:5993
 OnEnterHyperLinkTooltip = <function> defined @MRT/E

**Comment by Nnoggie** [comment]
wrong addon
