### ISSUE TITLE
Missing Stealth detection mobs

### ISSUE THREAD

**Issue by Bukama** [Nnoggie/MythicDungeonTools#447]
The following mobs have stealth detection, but are not marked as this.

**There are most probably more, but these are mobs I noticed:**

### Brackenhide Hollow:

* Bonebolt Hunter (185534)
* Vicious Hyena (185691)
* Rotbow Stalker (186208)

### Underrot

* Befouled Spirit (133685)

### Neltharus

* Qalashi Warden (193293)

**Comment by Wotuu** [comment]
It looks like my Keystone.guru -> MDT mapping (and vice versa) converter did not take TrueSight into account. I did map all the stealth-seeing enemies - let me see if I can rectify this.

**Comment by Wotuu** [comment]
I marked these as Truesight - I will go through MDT and mark them as well:

"name"
"Vicious Hyena"
"Rotbow Stalker"
"Fetid Rotsinger"
"Wilted Oak"
"Rageclaw"
"Overseer Lahar"
"Containment Apparatus"
"Flamecaller Aymi"
"Squallbringer Cyraz"
"Qalashi Warden"
"Bracken Warscourge"
"Nokhud Defender"
