### ISSUE TITLE
Underrot mobs missing / count are wrong

### ISSUE THREAD

**Issue by Bukama** [Nnoggie/MythicDungeonTools#448]
I noticed wrong / missing mobs and count in Underrot.

1) The count on many mobs in Underrot is wrong. I created this route in MDT, but with even more pulls I was at around 90% at the end. Can't tell now what is wrong, we have to investigate.

![wrong](https://github.com/Nnoggie/MythicDungeonTools/assets/4354359/49cee4d6-dea4-4a49-a432-e0e45819f4d9)

2) In MDT there are missing mobs / wrong groups

* G6 and G7 seem to be identical now (they were not back in BfA)
* In G19 and G20 there is also a worm (Grotesque Horror) in

**Comment by Wotuu** [comment]
I'm working on this now, thanks!
