### ISSUE TITLE
BH: Missing patrol paths 

### ISSUE THREAD

**Issue by Bukama** [Nnoggie/MythicDungeonTools#454]
At least Warscourge 22 is missing

![image](https://github.com/Nnoggie/MythicDungeonTools/assets/4354359/a030844a-7f72-4f7d-a01b-064228edd8ce)

**Comment by Wotuu** [comment]
I also added the patrol for these dudes. Not sure why it wasn't in there as I definitely put it in before.

![image](https://github.com/Nnoggie/MythicDungeonTools/assets/811809/f164454f-7ec4-4dd0-9e18-7e21161f63a7)
