### ISSUE TITLE
NL and BH: Remove non-existing packs

### ISSUE THREAD

**Issue by Bukama** [Nnoggie/MythicDungeonTools#455]
The following packs are shown in map, but don't exist in the dungon:

Brackenhide:

The three "Diseases Slashers" of G80. There are only the 4 Rothexers in the center. Checked on Normal and M+15

![image](https://github.com/Nnoggie/MythicDungeonTools/assets/4354359/be6fdf8d-de8b-4aa3-91ea-84bef5e0b5b1)

Neth Lair:

The three crocodiles (Gnasher 8,9,10) do not exist. There is no cave anymore and no mobs with nameplates (checked on normal and M+17)

![image](https://github.com/Nnoggie/MythicDungeonTools/assets/4354359/2a170ee3-4c21-4321-860a-20d2f72f766d)

![image](https://github.com/Nnoggie/MythicDungeonTools/assets/4354359/3a5b8786-87ac-4a84-85d2-6911b48d6768)

**Comment by Wotuu** [comment]
Also noticed that these 4 are missing in the mapping right at the start.

![image](https://github.com/Nnoggie/MythicDungeonTools/assets/811809/641ab11b-2d8e-4b4f-b4de-2be494f73bc5)

**Comment by Wotuu** [comment]
This pack here, I don't see it on normal nor on the M+ video I linked above either:

![image](https://github.com/Nnoggie/MythicDungeonTools/assets/811809/89c0060c-5510-45c4-953b-a446a68c116b)

**Comment by Wotuu** [comment]
There's actually 2 gutstabbers here:
![image](https://github.com/Nnoggie/MythicDungeonTools/assets/811809/180a9238-a020-4508-a19b-b1300d654acd)

![image](https://github.com/Nnoggie/MythicDungeonTools/assets/811809/02cf6b7f-8290-495c-b501-67440dd9fa60)

**Comment by Wotuu** [comment]
This one Bonecrusher does not seem to exist - it probably turned into one Gutstabber

![image](https://github.com/Nnoggie/MythicDungeonTools/assets/811809/f6ebd027-7471-4c9a-9e1d-8b913db84ffa)

![image](https://github.com/Nnoggie/MythicDungeonTools/assets/811809/99351371-bb49-438b-bbc8-108632064074)

**Comment by Wotuu** [comment]
Found this cheeky bugger hiding here:

![image](https://github.com/Nnoggie/MythicDungeonTools/assets/811809/a8d81a18-98c2-4633-874f-a6ffb1693a44)

![image](https://github.com/Nnoggie/MythicDungeonTools/assets/811809/592de735-2920-4ceb-b2d6-33154a615c47)

**Comment by Wotuu** [comment]
Same area, G68 has a Stalker and not a Hunter

![image](https://github.com/Nnoggie/MythicDungeonTools/assets/811809/f013b01b-ef39-4008-a47b-ae7de5333959)

**Comment by Wotuu** [comment]
Bonebolt Hunters also do not have Stealth Detection

![image](https://github.com/Nnoggie/MythicDungeonTools/assets/811809/18c27c0a-80a6-4c7c-9367-47abd1085ec1)

**Comment by Wotuu** [comment]
After defeating Gutshot first, a new Graveyard is opened (see the dialogue in the chat). I died and spawned here.

![image](https://github.com/Nnoggie/MythicDungeonTools/assets/811809/6619377f-cc10-4d52-a778-2fcc6302c14a)

**Comment by Wotuu** [comment]
On topic, need to add 3 Wither Biters and remove those marked in the screenshot

![image](https://github.com/Nnoggie/MythicDungeonTools/assets/811809/a972d8d6-0f7e-4ad3-b5cb-91ba05cd2101)

**Comment by Wotuu** [comment]
This guy also needs to go:

![image](https://github.com/Nnoggie/MythicDungeonTools/assets/811809/832f09bb-03e8-4745-b7cf-64bc35bc4a89)

**Comment by Wotuu** [comment]
One less Lasher here

![image](https://github.com/Nnoggie/MythicDungeonTools/assets/811809/ef4e7ce4-a110-4738-9503-3af94e096e62)

**Comment by Wotuu** [comment]
OK I processed all of these. I went through all of Brackenhide on normal and corrected anything that wasn't right and documented it all above.

**Comment by Wotuu** [comment]
I'm not so sure about that. I checked multiple sources and they went through that area to get to the 2 cages north of there and the pack wasn't there from the start. I may dip in again tonight and immediately go there and see if the pack's there. If it's one of those vanishing packs it's gonna be annoying but eventually I may have to create a system for these packs so that they are automatically removed/marked as unpullable when you did something (in this case open up the 5 cages).
