### ISSUE TITLE
Update for zhTW.

### ISSUE THREAD

**Issue by GnomeTW** [Nnoggie/MythicDungeonTools#464]
Update for zhTW:
Since the zhTW content has always been a mixture of zhCN and enUS versions, we have made modifications based on WCL data to ensure the correct NPC names in zhTW. Currently, we have only modified S2 Mythic Plus. We have been using it for a while and have overwritten it with our version whenever MDT is updated.

If you are willing to update zhTW, here are the modified contents by translator KalmiaTW. 

tks :D

[zhTW.txt](https://github.com/Nnoggie/MythicDungeonTools/files/11513201/zhTW.txt)

**Comment by Nnoggie** [comment]
added in next build
