### ISSUE TITLE
English translation contains Chinese characters

### ISSUE THREAD

**Issue by Hollicsh** [Nnoggie/MythicDungeonTools#467]
Hey Nnoggie !
On the courseforge website, in the "translations" tab, there are Chinese characters in English words, is this a bug ?

![Screenshot_2](https://github.com/Nnoggie/MythicDungeonTools/assets/54585769/0a65cad1-2381-4e22-a375-fd9008be55ba)

**Comment by Nnoggie** [comment]
fixed!

**Comment by Hollicsh** [comment]
@Nnoggie 
Again ...
![Screenshot_2](https://github.com/Nnoggie/MythicDungeonTools/assets/54585769/0f7d8be9-403d-4042-aa03-98bab3c81636)
