### ISSUE TITLE
HOI: Mapping issues

### ISSUE THREAD

**Issue by Bukama** [Nnoggie/MythicDungeonTools#471]
There are some mapping issues in Halls of Infusion (aside the missing stealth detection, see #470):

Missing Zealot patrol path (G21):
The two Zealots of G21 partolling up and down on the stairs

![image](https://github.com/Nnoggie/MythicDungeonTools/assets/4354359/36da46fe-3889-475a-b9c8-84f043eedb87)

Missing Zealot after first boss:

After the first boss, when heading towards the frog event there is a Zealot missing. The following screen shots the two dead Zealots with red and orange ingame markers. The missing Zealot is 

![image](https://github.com/Nnoggie/MythicDungeonTools/assets/4354359/dfa88734-a96c-49a9-ad8b-3cd306426cc1)

Before you pull it, it's located on the right when you enter the room. It does not seem to patrol

![image](https://github.com/Nnoggie/MythicDungeonTools/assets/4354359/18912573-b650-4345-bc80-c697c575585a)

**Comment by Nnoggie** [comment]
fixed
