### ISSUE TITLE
Brackenhide: Recent update messed up the last part

### ISSUE THREAD

**Issue by Kezwo** [Nnoggie/MythicDungeonTools#476]
The area around the last boss got messed up in v4.0.3.12. Was correct in v4.0.3.11.
The pack with the four Rothexers is now missing, and some of the packs right next to the last boss. Maybe even more, but these are the ones I noticed.

**Comment by Wotuu** [comment]
Looks like [725a2e4b679fa08c4a8c6c028b97c6b300f6ae25 ](https://github.com/Nnoggie/MythicDungeonTools/commit/725a2e4b679fa08c4a8c6c028b97c6b300f6ae25) messed it up.

**Comment by benhamlin** [comment]
I'm still seeing this is issue in v4.0.4.4, at least the pack of 4 Rothexers is still missing.
