### ISSUE TITLE
Uldaman - missing mob in G19

### ISSUE THREAD

**Issue by mabnp** [Nnoggie/MythicDungeonTools#477]
G19 has 2 warders and 1 Earthen Custodian (this missing mob). In the middle of the screenshot:

![https://i.imgur.com/BuUm2LP.jpeg](https://i.imgur.com/BuUm2LP.jpeg)

**Comment by Wotuu** [comment]
Verified with https://youtu.be/bKtAiOZqyig?t=696 as well.

![image](https://github.com/Nnoggie/MythicDungeonTools/assets/811809/064a7c6f-2be2-4763-957b-10e516ccce34)
