### ISSUE TITLE
Neltharion's Lair: Understone Drudges have incorrect NPC IDs

### ISSUE THREAD

**Issue by Wotuu** [Nnoggie/MythicDungeonTools#482]
![image](https://github.com/Nnoggie/MythicDungeonTools/assets/811809/29f9d9db-b9e8-4b9c-b7b3-d97e92958675)

**Comment by Nnoggie** [comment]
I fixed this now in [c0cfcfa](https://github.com/Nnoggie/MythicDungeonTools/commit/c0cfcfa747e2c81ecf152b9bffc487eee12826ce)
It's ugly, will make old routes incomplete but i dont really see a better solution.
