### ISSUE TITLE
MDT Stopped Loading

### ISSUE THREAD

**Issue by GarrettCottrell** [Nnoggie/MythicDungeonTools#486]
Instead of opening, one gets an endless spinning wheel on their screen. Here's the Lua Error Output when I try to open MDT - I asked around and others have experienced this same issue so wanted to mention it here:

Message: attempt to yield across metamethod/C-call boundary
[string "=[C]"]: in function `yield'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:2383: in function `UpdateMap'
[string "@Interface/AddOns/MythicDungeonTools/Modules/Maximize.lua"]:54: in function <...rface/AddOns/MythicDungeonTools/Modules/Maximize.lua:7>
[string "=[C]"]: in function `Maximize'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:4810: in function <...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:4563>
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:405: in function `ShowInterfaceInternal'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:103: in function <...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:103>

Time: Fri Jun  2 09:18:19 2023
Count: 1
Stack: attempt to yield across metamethod/C-call boundary
[string "=[C]"]: in function `yield'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:2383: in function `UpdateMap'
[string "@Interface/AddOns/MythicDungeonTools/Modules/Maximize.lua"]:54: in function <...rface/AddOns/MythicDungeonTools/Modules/Maximize.lua:7>
[string "=[C]"]: in function `Maximize'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:4810: in function <...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:4563>
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:405: in function `ShowInterfaceInternal'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:103: in function <...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:103>

[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:4545: in function <...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:4526>

Locals: self = Frame {
 0 = <userdata>
}
elapsed = 0.040000
start = 1559018.705600
hasData = true
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 DrawAllHulls = <no value>
 showInterface = <no value>
}
(for control) = "showInterface"
name = "showInterface"
func = <no value>
ok = false
msg = "attempt to yield across metamethod/C-call boundary"
max = <function> defined =[C]:-1
pairs = <function> defined =[C]:-1
coHandler = <table> {
 RemoveAction = <function> defined @Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua:4514
 AddAction = <function> defined @Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua:4503
 frame = Frame {
 }
 update = <table> {
 }
 size = 2
}

**Comment by Nnoggie** [comment]
fixed in [5a55054](https://github.com/Nnoggie/MythicDungeonTools/commit/5a55054d618b2627f149d3d0937b6a7225caaabd)
