### ISSUE TITLE
Update for  zhCN 

### ISSUE THREAD

**Issue by nanjuekaien1** [Nnoggie/MythicDungeonTools#488]
Complete the missing localization of zhCN

[zhCN.zip](https://github.com/Nnoggie/MythicDungeonTools/files/11644886/zhCN.zip)

**Comment by Nnoggie** [comment]
Thanks! Will be added in the next release.

**Comment by nanjuekaien1** [comment]
I went to add localization on curseforge and found that it couldn't.
I can only send it to you for help.

**Comment by nanjuekaien1** [comment]
Duplicate + wrong documents on curseforge.
![错误的文笔](https://github.com/Nnoggie/MythicDungeonTools/assets/2303601/8f44f27b-5fef-4243-b379-3d0a50147f1c)

**Comment by nanjuekaien1** [comment]
L["Select all"] = "全选"
L["copiedToClipboard"] = "复制!"

**Comment by nanjuekaien1** [comment]
L["Subterranean Proto-Dragon"] = "Subterranean Proto-Dragon"
L["Gusting Proto-Dragon"] = "Gusting Proto-Dragon"
Can you help provide NPCIDs for the above 2 places? I didn't find it in the file
Thanks

**Comment by nanjuekaien1** [comment]
Thanks

L[ [=[Bounty stacks 
after this pull]=] ] = [=[这波怪击杀后
赏金层数]=]
L["copiedToClipboard"] = "复制！"
L["Select all"] = "全选"
