### ISSUE TITLE
Empty error frame when encountering errors

### ISSUE THREAD

**Issue by ljosberinn** [Nnoggie/MythicDungeonTools#496]
![image](https://github.com/Nnoggie/MythicDungeonTools/assets/29307652/96fb42f5-aa0d-47e5-8e78-75de9e780c54)

bugsack however caught:

```lua
1x MythicDungeonTools/Modules/ErrorHandling.lua:208: script ran too long
[string "@MythicDungeonTools/Modules/ErrorHandling.lua"]:208: in function `DungeonEnemies_AddOrRemoveBlipToCurrentPull'
[string "@MythicDungeonTools/Modules/DungeonEnemies.lua"]:330: in function <MythicDungeonTools/Modules/DungeonEnemies.lua:317>

Locals:
(*temporary) = <table> {
}
(*temporary) = false
(*temporary) = false
(*temporary) = "script ran too long"
currentFunc = "IsCurrentPresetTeeming"
funcName = "DungeonEnemies_AddOrRemoveBlipToCurrentPull"
func = <function> defined @MythicDungeonTools/Modules/DungeonEnemies.lua:895
onError = <function> defined @MythicDungeonTools/Modules/ErrorHandling.lua:154
addTrace = true
caughtErrors = <table> {
 1 = <table> {
 }
}

```

**Comment by Nnoggie** [comment]
Do you remember what you were trying to do in the AddOn when this error occured?

**Comment by ljosberinn** [comment]
I think I just clicked off a pack, or added a pack, one of those

**Comment by Tabbytibby** [comment]
ReloadPullButtons: .../ElvUI_Libraries/Core/Ace3/AceGUI-3.0/AceGUI-3.0.lua:173: attempt to index local 'widget' (a nil value)

16/07/23 00:57:37
MDT: 4.0.4.14
Client: 100105 enUS
Character: Kittywinky-Frostmourne (US)

Route:
!TvvWUTnmm0FPil5iRRB7sb2YkMZPDGajPsDE11EirURBF9vu0sMYoabX2s8r(4JKsGaocTp15CDxM69)douvdT)1AFboiH23o1pzrlUmD9QDW)4uFpCquNxOD6CV9nlUi0ETZ5)UZDZ6VfWeWFe8bhgF4Zq(Y0WZ2XHhE69WEvqR3AFTB4z4m0EZ2BV47ghq4IyGc4(tiO3OvosUlUh6Bj)dv(JGr4pj(lSrnZQ2lJ9JxHwNtADUWAM5nJwwTlz6UiNJrlbbbySlmOIhufpqveyjdmgpza8(7bwhPBd3fkYfQI4BikZZNeenj2cv85suDNXO2KtsmqPxc2Bk2qfFPo(sv8LOWM1iAzDHsvLYu0WuTMstnV60u4ddV6TNXyuKrgBY7LnxSFDu08OuZJsnLO7Ij0EEW0RAcmSGPj3sozoN08c8k5fjlwrAitnZ8l5oHkRumnsWvL5Cbz69RqZUDHXMybvW12mEnW6LtsrZsrtMxINd0GGHTxIMjBojOIsY)Zetubh3oqTFfZIbnjcIYofsqxAlQZ6NF9y3IXIvUAhu2YtdAZEbnOoZGiVMLyvHtuRQd6ndeLDPMYtpAyTPIIszDoDjLJoyIigjv5dX0fkIe2ohVPddpMILA6ccOG71HLOkYpCarfrqeIkWkMaNAjoSTOiPIstUOKAnkRYl96RpBko8TKojqnmqRN0YClFgqm53mEiN32N9XJN6TEV9Hb3ic40KF8Z464vpFALn4vtO4fUB69W)hgV(6PEOD88VdxpDJYIPUNcxyzE5NF9)F7xMFGKf(4p

Stacktraces

ReloadPullButtons:
[string "@Interface/AddOns/MythicDungeonTools/Modules/ErrorHandling.lua"]:213: in function `ReloadPullButtons'
[string "@Interface/AddOns/MythicDungeonTools/AceGUIWidgets/AceGUIWidget-MythicDungeonToolsPullButton.lua"]:1120: in function `Drop'
[string "@Interface/AddOns/MythicDungeonTools/AceGUIWidgets/AceGUIWidget-MythicDungeonToolsPullButton.lua"]:254: in function <...idgets/AceGUIWidget-MythicDungeonToolsPullButton.lua:253>
[string "=[C]"]: in function `Hide'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:176: in function `Release'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:468: in function `ReleaseChildren'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:3672: in function <...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:3665>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/MythicDungeonTools/Modules/ErrorHandling.lua"]:208: in function `ReloadPullButtons'
[string "@Interface/AddOns/MythicDungeonTools/AceGUIWidgets/AceGUIWidget-MythicDungeonToolsPullButton.lua"]:1120: in function `Drop'
[string "@Interface/AddOns/MythicDungeonTools/AceGUIWidgets/AceGUIWidget-MythicDungeonToolsPullButton.lua"]:254: in function <...idgets/AceGUIWidget-MythicDungeonToolsPullButton.lua:253>

**Comment by Nnoggie** [comment]
these should be fixed now
