### ISSUE TITLE
Error codes, tried inserting a note

### ISSUE THREAD

**Issue by Demonicgoose** [Nnoggie/MythicDungeonTools#505]
GetScale: ...erface/AddOns/MythicDungeonTools/Modules/Toolbar.lua:1118: attempt to call global 'QuestPOI_CalculateNumericTexCoords' (a nil value)

16/07/23 14:37:00
MDT: 4.0.4.14
Client: 100105 enUS
Character: Demonicgoose-ArgentDawn (Europe)

Route:
!fsvBpsniq4FrNbMbkWhvpVenM6Lu)mj7lWLvRTMDBpV7FVmaTfAmEzB2odmZZ8mVvl3(DB34XF4onDli2g1pNKEqAmmJgemHaygLX6VtiSTG9H7KOgqUqAymbkyQ8vi5xRW(bBR02zNSDdb5jYNcCB4mJu1iaTgvmoSIB7DGgENgdgi4ax9)qeRrSjGKHdG2GgfuWuHbeALbzCuBAeS3IPIkCzgGhsqPqIIgUPcxwJqOqeuCg0yElCLL4QdzT0ekInmLsiKLvwgNhYduGGbvs8nWni8hN7N0TDZxoB7E)v3x9ZF6v9LVy7on2pE9Xd9UPj3Nh8Jehompn(r68ldpfGO2MZVqbja6K7LW)378hM7dcNV49xofeFnejMT75d9ZocTtZxV6gMECUVpCdUEq38XE3ZU(iXU56ddyxghsPpz30QL3pp8KBCigAnfy3ViMD02D9IF6BE)n32SzmH)DiyRNS8h9aXhKsb6rt1QwJTTjkOIxPJQMOAitA5bno5oPh8MRJ8lDh1tO3bVbETTWIT0BtYhyXhE6SOnYL5)ssMh02inFzgjz1eXYcfvPcuRvAyQBA78E059RBE5tPZmUip3CjVlrjwjQIsnDPcUOSpGyaA(oOfvqdLGbvGbfGHodX(qxQSQL2cWeUXsLQeP1ilROL)irRfKAIwI1CSzxjkMh4kAPypTbIUSJK5tsfloCJqQie6DvlQrWRQYMk75IeY6DSJkmaVodIEUe80Nstt7YOAkRRMUefmDJvgQyTrDCLqL(d76gBKloZTLuP2stvtSC)ugFW4cztKXQ4(PoUFAkPzUwehKwI3bEQvb7AN88Yg91I44FEmldxE4j33ZTUP8wf9wwq)D7tPLnkg6DedT)J1mOIyPF2)o

Stacktraces

GetScale:
[string "@Interface/AddOns/MythicDungeonTools/Modules/ErrorHandling.lua"]:213: in function `DrawNote'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:4269: in function <...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:4252>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/MythicDungeonTools/Modules/ErrorHandling.lua"]:208: in function `DrawPresetObject'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:4247: in function <...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:4240>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/MythicDungeonTools/Modules/ErrorHandling.lua"]:208: in function `DrawAllPresetObjects'
[string "@Interface/AddOns/MythicDungeonTools/Modules/Toolbar.lua"]:927: in function <...erface/AddOns/MythicDungeonTools/Modules/Toolbar.lua:914>
[string "=[C]"]: in function `xpcall'
[string "

**Comment by Demonicgoose** [comment]
![image](https://github.com/Nnoggie/MythicDungeonTools/assets/139691381/ba6a2197-2e5e-496f-bdf6-a58bd96e3237)

**Comment by Nnoggie** [comment]
Bug has been fixed, make sure to update to the latest version 👍
