### ISSUE TITLE
GetScale error

### ISSUE THREAD

**Issue by glcorreia** [Nnoggie/MythicDungeonTools#508]
GetScale: ...erface/AddOns/MythicDungeonTools/Modules/Toolbar.lua:1118: attempt to call global 'QuestPOI_CalculateNumericTexCoords' (a nil value)

26/07/23 14:10:25
MDT: 4.0.4.10
Client: 100105 enUS
Character: Bonk-Aggra(Português) (Europe)

Route:
!nsvxVTTom0FrPWY67x79EdwhW1lfkOpk0Kg5c35zpKi319s)TprrzBz3a0HyyetYZHKhsjlXU3Ao1ux380qR)32kk3A(LZ9DBvP1m0CYAE4(xFP5(h4QV(FwZRhAhCaMNgoF2153n02ARiQjdMHJTUxDGrR5CtT)B11xC(lbmbg3B9HFJX(VdDp767U70B2kM2A8o3pA6E2E0AU4ADp5B67aCKygc4(ziBxqlZVGNY4dfE8yEUQdAYbALKCuXGhp8AehuJ9T9NTM6AQRUoJvmewKbEeUy0Bwgej)zSowkZCdmRDzWWaL59aBMOrUvrtYyU15zGTQUPUmV5y1rSKICW8ffMo108fcnlVYu51ebRtcDHowGgxQN1hX6sSG6Ym8L5cXugqjme4sbejtUGmu9jOerwmfcz4d0aKGZbfefpBniwLEqX2VkVO(a2NPrdT2yJnTLLcRkBJCUIRwVK6J62(uTC1LvzCZtKZYQ5kgvwIzxz5BCXMqYAIdKOKo1eISf9fmkJouPkghzKCLd7I0xF84eHML10jHrEqmqq4yJANxWH55(KEaFPwmzsR9JahvpeOiJMzIgjNVGC2e5vzBYrzOmDJbQkF4uZCU5P8G5vnzfyqGJkKlcAwhnlJpQjncNc51p3ETZte5kbnQd6vcQYUF9EFvzXIGIxr7DVfE)LD7m))7pU59h32F23KqU7qRZ7D31v3dSDyW3)pGD4U7Bxft8UDGW(JVeUrF62BZPXCwUwAVf6qOXGZyGISjE5FlcWWiL3e3knB4ff3efsdnymU2B2WuYBkITacyBWIGj0fLAPOGQzcB9gEA2uMvkBfuwPGtPcLGkymEiow8GZ2nkoxZvLfAfLXfH5f6AzjdjTl8)0Twz8s5AjxOzfYsMKUGxPwqyAAGzMkS58j8Y(BRxfHsPsQGiLHYw8j8c)S)5d

Stacktraces

GetScale:
[string "@Interface/AddOns/MythicDungeonTools/Modules/ErrorHandling.lua"]:213: in function `DrawNote'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:4269: in function <...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:4252>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/MythicDungeonTools/Modules/ErrorHandling.lua"]:208: in function `DrawPresetObject'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:4247: in function <...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:4240>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/MythicDungeonTools/Modules/ErrorHandling.lua"]:208: in function `DrawAllPresetObjects'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:2550: in function `UpdateMap'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:3017: in function `copyCallback'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:3049: in function <...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:2956>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/MythicDungeonTools/Modules/ErrorHandling.lua"]:208: in function `ImportPreset'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:2790: in function <...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:2786>
[string "=[C]"]: ?
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:66: in function <...terface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua"]:22

**Comment by Nnoggie** [comment]
update the addon to the latest version, this error was fixed already 👍
