### ISSUE TITLE
Freehold Deckhands near Council o Captains have the wrong NPC ID

### ISSUE THREAD

**Issue by Wotuu** [Nnoggie/MythicDungeonTools#509]
https://github.com/Wotuu/keystone.guru/issues/1903#issuecomment-1658161019 

Should be 130521

**Comment by Wotuu** [comment]
![image](https://github.com/Nnoggie/MythicDungeonTools/assets/811809/10c994ae-7200-4744-bcd8-ff9106ed5c1b)
![image](https://github.com/Nnoggie/MythicDungeonTools/assets/811809/a37222df-c033-4415-8fed-31d65f053a7c)


These 4 are also 130521

**Comment by Wotuu** [comment]
These 3 too
![image](https://github.com/Nnoggie/MythicDungeonTools/assets/811809/faef0984-dcc3-466f-8953-a7f81b309b2a)

**Comment by Wotuu** [comment]
These 5 too
![image](https://github.com/Nnoggie/MythicDungeonTools/assets/811809/fba9ae63-763d-4753-a419-e428368a9f48)

**Comment by Nnoggie** [comment]
Is this fixed with #510 ?
