### ISSUE TITLE
MDT Issue

### ISSUE THREAD

**Issue by Todeshau** [Nnoggie/MythicDungeonTools#522]
1x: showInterface: ...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:401: attempt to index field 'HelpButton' (a nil value)
1x: GetDB: Interface/SharedXML/Pools.lua:390: assertion failed!
1x: POI_CreateFramePools: Interface/SharedXML/Pools.lua:390: assertion failed!

11/08/23 22:54:29
MDT: 4.0.4.26
Client: 100105 deDE
Character: Zâøøgâ-Eredar (Europe)
Out of combat
Zone: Thaldraszus (2112)

Route:
!TN1sZTnYr4FlzV4KuRPjErcKdPkBToRStfkvIkLRCbfhsmqywcIHzWarRCG)2t)aaCgskVXj54ErcpMP7V(R75RBiLhK)y(s96FrUX2cxUGUVGVAzCw6KW8fH5lFBuA4K48fr4ZxeN)H8fj5lxAvnBxBKcB1XvfAz7XvIJRkvFvyLfWfgDJvuFCfTUJR(q)kfRv1k7lhxzRe2JR(jvR2OKn22jtGfjBHNz1hx1Afnf4Vu1GnuLhx9IUd2TrcVxyEscozsUnFzdahlcthONfmjLrEW8y8sFKhaE6tnwPX0ThDxLeHNyZwzZXvFryA3O7ap8giIUvvi1DWf3aVUgwN20JKdeWkLaIk(XJR23H3k)Q1aKWo96w4zueuOKG7o(5Wjiv018ULvQNF3sTgC77E0iA(NDaH8VunpbVVs)RGNhepbuK2S7hrBgb28HoyrIdIxyS1AX7jtCtT4WXv)f1tvqOIBMZnoKwKlP1tviRfgoht9)gRDvwl2L1cNNmjQVwlB2K5)gR9kSwIhRLnDYS(ATOzNZzpwPilagdo6dxUPsOTQnuS5qMvsrnGnZjuH6e9kqWl2s0gHpR2k3nqt4(Ka(31HQnfQ29sCDIMTUkkZCbCY0Sjb9IHHjtUaYFrudACD779GWO7WFRj(bdHkalogFUhBah3Y6RHsYUuPL5JwO8aY9qQIzFkU2lSgDnqmhQuBQKpJHfUyPOvjnoom1pAMIEHIMKlC3nqz2BXSlqtGtk4AmK2my5fhQ6HmVrJacLS)LUD7XxGxZVIZGvCAaEQ4zTQGRFPAqAvN5h3uqMlONLenCslC(8jjNd7)k5MhXeDRJncM(krE8SGliAJuUt3HTP2OBA72Hn1iq2GN9WQL91Ixqs(GcYRdCWtW(GR3OmBQLVJpEIVSVxhqA3tBdZIv6U6cSABlww2zAGhcDZSeH8gOhPS5nmBz0w4oOavSt8e96c56UYYHAmMmLnM(3sqzTUfmyrNSNXpU6h2PABj2f45FaKzE)93)pGtS3E3F7(pT4Nr9jWKnAm1jjS06cKtgDTCJMyeYLu)Eehy5wxdEMsSUw6gRihbwF3UUgLvHBaEMqzX1d917nEPYqn9vuHnaLBiQNcPhV9JlapGwq6wye4nPY8uu39vetUJgVr9S8pb6xYA4Gb4ZeuKDp(uWhDTBfgdgFLAA8churr(N)J32RymK92utODdqdmMzrWlm5VFDnMj(Da5lmBB)d9ugT6nmhUr0GmF9liaGR2lBWKfufYwg481cRBS7nQtyA6qbDiimDrj9n6D7RL0ez)VZeUOWB2H40SbueKCfu8WyJcrrrlE4yuKaAIThRvQWtq7hkDO586vYHsQ3xxRpG9eqHpa4az9(7(OlC8AkNMmm5AqwikACgN8Fu2Z16EnVcMf8nQ3((n(m)EbthnEC2vYNF3M3VvtsW44kPbx2Q5738EnwcNnDCY7zxOq)9B8m)buhjMRmu)9p8P7GjqU7M)(sWuV)HF(JpI15Alm8qdRUs9gCmFOxRHW4OrSNfFzvZ)noW)dQcIhNHaklZ()Hd80cINpohryY8lRDESc(gScVjhgeX5E308l16XMj1YcmvHNvR4DQpimfdnfxBu07F7F(c5Hqp5HK5ZgfPIIUC6PB7EAqT5GaBE6Gjx8ua9DWb

**Comment by Nnoggie** [comment]
Hello! 
Could you describe what you did when this error occured?
Also if you dont mind, a list of other installed AddOns would be helpful to track this one down.
Thank you!

**Comment by Nnoggie** [comment]
I think i figured this one out, double clicking the minimap icon produces a similar error.

**Comment by Nnoggie** [comment]
fixed in [d7f37b0](https://github.com/Nnoggie/MythicDungeonTools/commit/d7f37b09b67cac2c4036018c5a2e71a326fc0b8a)

**Comment by Todeshau** [comment]
Hey, sorry didn't notice my your E-Mail, but the issue was, that I importet
a route from a dude in underrot and then it just went crazy. All Routes
took massiv long to load or they just went into eachother. If needed, I can
do screenshots of my Addons, because to do a list is to much.
Best regards Todeshau( Dominique)

Nnoggie ***@***.***> schrieb am Fr., 11. Aug. 2023, 23:03:
