### ISSUE TITLE
Tutorial frames incorrect positioning

### ISSUE THREAD

**Issue by Hollicsh** [Nnoggie/MythicDungeonTools#524]
I don't know, was it supposed to be like this ?

![Снимок экрана 2023-08-13 155405](https://github.com/Nnoggie/MythicDungeonTools/assets/54585769/e2a8851a-a0d2-4473-8c75-4c7c6ce3f606)

**Comment by Nnoggie** [comment]
Hmm the problem seems to be with UIScale.

**Comment by Nnoggie** [comment]
decided to remove the tutorial system completely
