### ISSUE TITLE
I don't know, it's weird

### ISSUE THREAD

**Issue by Hollicsh** [Nnoggie/MythicDungeonTools#533]
1x: IsWeekInspiring: ...AddOns/MythicDungeonTools/Modules/DungeonEnemies.lua:964: bad argument #1 to 'pairs' (table expected, got nil)

19/09/23 16:10:28
MDT: 4.1.0.7
Client: 100107 ruRU
Character: Сладкаячерри-СвежевательДуш (Europe)
Out of combat
Zone: Тальдразус (2112)

Route:
!D5ySonmmqy4NPeyH1clDXej35tnj9UixCTRSphclDHb26RaVcmwjO5zW5nc7ebdv26KUF9))D)qbSbK7uePAdA(nquwcYxr8fq8ai7R1bm7On4COHRcAnik(FxgA0ypUO5ue)mrEK9PiP4Bao9(Z7tbthAnR3naI7tSzepOmDqdi9OgBzL1KZvK)Pyht3YViKlGvBDGKO7qIM5YzedPz8Z44PTtVh)jog)E6J4xXRXltNbPTzFIRFUileQQ1iZ4AdzZuRdS9XSEUiRUXZCrNpe87
Stacktraces

TableToString:
[string "@Interface/AddOns/MythicDungeonTools/Modules/ErrorHandling.lua"]:297: in function `DungeonEnemies_UpdateBlipColors'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:3192: in function <...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:3169>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/MythicDungeonTools/Modules/ErrorHandling.lua"]:292: in function `ColorPull'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:2724: in function <...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:2713>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/MythicDungeonTools/Modules/ErrorHandling.lua"]:292: in function `ClearPreset'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:4005: in function <...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:4004>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:66: in function <.../ElvUI_Libraries/Core/Ace3/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/AddOnSkins/Libs/Ace3/AceGUI-3.0/widgets/AceGUIWidget-Button.lua"]:22: in function <...Libs/Ace3/AceGUI-3.0/widgets/AceGUIWidget-Button.lua:19>

**Comment by Nnoggie** [comment]
probably fixed in 10.2 release https://github.com/Nnoggie/MythicDungeonTools/commit/2086509398079f819ffdf512aa82fea9a5507d92

**Comment by Hollicsh** [comment]
Thank
