### ISSUE TITLE
[Feature Request] Prevent Duplicate Routes on Import

### ISSUE THREAD

**Issue by AngelTomkins** [Nnoggie/MythicDungeonTools#535]
Description:

Players often share routes with their groups to optimize dungeon runs. Currently, when a player imports a route that they already have saved, it creates a duplicate copy of that route rather than opening the already saved route. This can lead to cluttered route lists and confusion for players.

Feature Request:

I propose implementing a feature that utilizes hashing to identify shared routes and prevent the creation of duplicate copies. When a player imports a shared route that matches an existing route based on its unique hash, the addon should intelligently open the existing route rather than creating a duplicate.

Use Case:

    Player A shares a dungeon route with Player B.
    Player B imports the shared route.
    If Player B already has a route with the same hash (indicating it's the same route), the addon should open the existing route instead of creating a new copy.

Expected Behavior:

    When importing a shared route, the addon should check the route's unique hash.
    If a route with the same hash exists, the addon should open the existing route without creating a new copy.
    If no matching route is found, the addon can proceed to create a new route as usual.

**Comment by Nnoggie** [comment]
Functionality to detect duplicates and ask the user to update / copy always existed, but somehow this has been bugged for years.
Fixed here: https://github.com/Nnoggie/MythicDungeonTools/commit/f168574bbc97ddec85ff39afd9a5f7b78c560831
You can download and test the alpha version with the fix here: https://github.com/Nnoggie/MythicDungeonTools/releases/tag/v4.1.0.7-alpha

**Comment by Nnoggie** [comment]
fixed in v4.1.0.8
