### ISSUE TITLE
zhCN-S3-Throne of Tides

### ISSUE THREAD

**Issue by nanjuekaien1** [Nnoggie/MythicDungeonTools#542]
Thanks

[zhCN-S3-Throne of Tides.zip](https://github.com/Nnoggie/MythicDungeonTools/files/12836261/zhCN-S3-Throne.of.Tides.zip)

**Comment by Nnoggie** [comment]
thank you!

**Comment by nanjuekaien1** [comment]
L["Ink of Ozumat"] = "厄祖玛特的墨汁"

Thanks
