### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by overpowerz** [Nnoggie/MythicDungeonTools#550]
10x Couldn't open MythicDungeonTools/Bindings.xml
![image](https://github.com/Nnoggie/MythicDungeonTools/assets/9782609/deec6309-7163-4b8a-88b1-e1596229e8bd)

**Comment by Nnoggie** [comment]
This file has not been part of MDT for a long time and is not referenced anywhere in the code in latest version. What version of the AddOn are you running? Reinstall the AddOn from wago or curseforge and try if the error still happens.

**Comment by overpowerz** [comment]
Alright i will reinstall it and c if there same error
