### ISSUE TITLE
Linked mob error in Darkheart Thicket

### ISSUE THREAD

**Issue by DeeRez** [Nnoggie/MythicDungeonTools#551]
The second pack after Archdruid Glaidalis consisting of two Vileroot Blossoms, one Rotheart Creeper and one Rotheart Dryad is marked as a four mob linked pack. However if you pull the dryad when she jumps away from the pack she can be pulled without the rest of the mobs aggroing.

**Comment by Nnoggie** [comment]
Group connections in MDT do not reflect if NPCs are linked together in the game world.

**Comment by DeeRez** [comment]
Oh, I didn't realise. How do I mark just the dryad for my route without marking the rest of the pack? I don't want the dps blowing up the mobs I don't want to pull.
