### ISSUE TITLE
Localisation-zhCN

### ISSUE THREAD

**Issue by nanjuekaien1** [Nnoggie/MythicDungeonTools#557]
Nnoggie can't link to Discord with the recent internet control, Localisation has a new one, I saw it and came here to submit it.

**Comment by nanjuekaien1** [comment]
L["Use forces count"] = "在侧边栏使用部队计数"

**Comment by Nnoggie** [comment]
Thank you! This phrase needs an update:

https://github.com/Nnoggie/MythicDungeonTools/commit/6a88d72e39b31cd92f4d2a4486fdb42b685c5382

**Comment by nanjuekaien1** [comment]
L["LargePresetWarning"] = "你正在分享一组超大路线数据(传输时间: %.1fs)%s建议你使用导出功能，通过其他方式分享你的这组路线数据或从路线中删除绘图。%s你确定还要分享这组路线数据吗？%s"

Thanks
I wish you a Merry Christmas in advance.

**Comment by Nnoggie** [comment]
Thank you!

**Comment by nanjuekaien1** [comment]
L["Enable Compartment Button"] = "启用间隔按钮"

**Comment by nanjuekaien1** [comment]
@Nnoggie 
L["chatNoninteractiveWarning"]  = "聊天窗口启用了非交互模式，你将无法点击MDT路线。"
