### ISSUE TITLE
Wrong Mob in Rise

### ISSUE THREAD

**Issue by moodsen** [Nnoggie/MythicDungeonTools#558]
G2 in Doti Rise are atm one vanguard and one magus. The magus is wrong. Its a second Vanguard

**Comment by Nnoggie** [comment]
clip or vod please

**Comment by moodsen** [comment]
> clip or vod please

https://youtu.be/eo39RekBPbo?si=dQfLdNaa8Pij5QU3&t=18

**Comment by Nnoggie** [comment]
Thanks, unsure how this slipped through the cracks.
