### ISSUE TITLE
Spinning wheel

### ISSUE THREAD

**Issue by mbrierley1** [Nnoggie/MythicDungeonTools#567]
click on minimap button and all I get is a spinning wheel and two icons to open an issue.

**Comment by Nnoggie** [comment]
Please specify your problem. What version of the game and AddOn are you using? When does the problem arise? Provide error logs if possible through BugGrabber/BugSack AddOns. If you were using a route imported from a 3rd party please provide a link to it. Also if possible provide your MythicDungeonTools.lua from C:\Program Files (x86)\World of Warcraft_retail_\WTF\Account<accountname>\SavedVariables
