### ISSUE TITLE
i dont know 

### ISSUE THREAD

**Issue by hasi2014** [Nnoggie/MythicDungeonTools#575]
1x: MakeTopBottomTextures: ...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:666: bad argument #1 to 'SetJustifyV' (Usage: self:SetJustifyV(justifyV))
1x: MakeCopyHelper: ...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:811: bad argument #1 to 'SetJustifyV' (Usage: self:SetJustifyV(justifyV))
1x: DisplayErrors: .../AddOns/MythicDungeonTools/Modules/ErrorHandling.lua:184: attempt to index local 'externalButtonGroup' (a nil value)
1x: MakeSendingStatusBar: ...e/AddOns/MythicDungeonTools/Modules/Transmission.lua:698: bad argument #1 to 'SetJustifyV' (Usage: self:SetJustifyV(justifyV))
1x: showInterface: ...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:4993: bad argument #1 to 'SetJustifyH' (Usage: self:SetJustifyH(justifyH))

14/05/24 20:21:07
MDT: 4.4.0.5
Client: 100207 deDE
Character: Hasixii-Rexxar (Europe)
Out of combat
Zone: Thaldraszus (2112)

Route:
!D5y3kimmmu4xjxreVw9MDZyq86a9NSX0yRutMZ3EBhIGsHc5W35lbBWZieMggM8klVWUMni8KORy3oeMTSsvcVMZuu6vMliFNb1X0m9t2jnosPyByPkRyti62uCeDiCV0)rXx36A9joLrWy27mguwFf6LYpi2yWMdiKCxiVuljFA0BzseQnoKQwSQKowZR74WFm1Jy7Qy8n
Stacktraces

TableToString:
[string "@Interface/AddOns/MythicDungeonTools/Modules/ErrorHandling.lua"]:282: in function `MakeTopBottomTextures'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:4842: in function <...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:4774>
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:362: in function `ShowInterfaceInternal'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:75: in function <...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:75>

TableToString:
[string "@Interface/AddOns/MythicDungeonTools/Modules/ErrorHandling.lua"]:282: in function `MakeCopyHelper'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:4843: in function <...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:4774>
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:362: in function `ShowInterfaceInternal'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:75: in function <...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:75>

TableToString:
[string "@Interface/AddOns/MythicDungeonTools/Modules/ErrorHandling.lua"]:282: in function `DisplayErrors'
[string "@Interface/AddOns/MythicDungeonTools/Modules/ErrorHandling.lua"]:228: in function <.../AddOns/MythicDungeonTools/Modules/ErrorHandling.lua:227>

TableToString:
[string "@Interface/AddOns/MythicDungeonTools/Modules/ErrorHandling.lua"]:282: in function `MakeSendingStatusBar'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:4873: in function <...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:4774>
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:362: in function `ShowInterfaceInternal'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:75: in function <...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:75>

showInterface:
[string "=[C]"]: in function `SetJustifyH'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:4993: in function <...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:4774>
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:362: in function `ShowInterfaceInternal'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:75: in function <...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:75>

**Comment by Nnoggie** [comment]
update the addon
