### ISSUE TITLE
Wrong ID NPC (or no ?)

### ISSUE THREAD

**Issue by Hollicsh** [Nnoggie/MythicDungeonTools#602]
https://www.wowhead.com/npc=216342/skittering-assistant

![Screenshot_1](https://github.com/user-attachments/assets/2f8d8cea-7dfa-4cd1-8aee-84266042feaf)

**Comment by Hollicsh** [comment]
@Nnoggie sorry for ping, but still relevant

**Comment by Nnoggie** [comment]
The npcId is correct, the name has changed since beta. Good spot!
https://github.com/Nnoggie/MythicDungeonTools/commit/007b6e879de1719ca846948cf6d9bdfb5ee5b976
