### ISSUE TITLE
Unable to load /mdt

### ISSUE THREAD

**Issue by eapdaniel** [Nnoggie/MythicDungeonTools#606]
I cannot load /mdt in-game. The icon does not appear on the minimap.

Tested with :
- Manual installation
- Installatation/re-installation via CurseForge

See in folder and in-game screenshots
<img width="668" alt="Screenshot 2024-09-20 114033" src="https://github.com/user-attachments/assets/57f64b62-6479-4806-ab8a-1583760d1fcd">
<img width="814" alt="Screenshot 2024-09-20 113945" src="https://github.com/user-attachments/assets/f4a049f0-b0e5-4925-9dda-f6e2979ae546">

Note: I've also installed MDT Guide, and have successfully use /mdtg help to print the help message.

**Comment by CeeKayH** [comment]
i have the same issue

**Comment by CeeKayH** [comment]
@Nnoggie great job, it is working again. Thanks!
