### ISSUE TITLE
5.0.11 Lua error on login

### ISSUE THREAD

**Issue by Nokramx** [Nnoggie/MythicDungeonTools#607]
getting following lua error on login after updating to new MDT version:

2x MythicDungeonTools/libs/load_libs.xml:4 Error loading MythicDungeonTools/CallbackHandler-1.0-8/CallbackHandler-1.0.lua

**Comment by TylerPentecost** [comment]
It looks like 8f88a680cbfb22592be1e3711cd3a8d1e4c1c9cb added a reference to CallbackHandler-1.0, but that libarary is not packaged up with the addon.
![image](https://github.com/user-attachments/assets/5fffe29e-0531-4ee8-9931-8489de51433a)

**Comment by TylerPentecost** [comment]
It looks like the reference to CallbackHandler-1.0 was removed a few weeks ago in 3c6b1d2e93e5e5fe3d419972c542a4de5952413f. I imagine adding this back in will resolve the issue.

**Comment by Nemesis2354** [comment]
Same Error

3x Interface/AddOns/MythicDungeonTools/libs/load_libs.xml:4 Error loading Interface/AddOns/MythicDungeonTools/CallbackHandler-1.0-8/CallbackHandler-1.0.lua

Locals:
nil

**Comment by berezerker** [comment]
same error
Message: Interface/AddOns/MythicDungeonTools/libs/load_libs.xml:4 Error loading Interface/AddOns/MythicDungeonTools/CallbackHandler-1.0/CallbackHandler-1.0.lua
Time: Sat Sep 21 22:32:51 2024
Count: 2

**Comment by Nnoggie** [comment]
fixed
