### ISSUE TITLE
Damage number in addon does not match the number in the game

### ISSUE THREAD

**Issue by takato3000** [Nnoggie/MythicDungeonTools#612]
Hi there,
Here's some infos about the game, the addon version, and server realm info.
Game version: 11.0.2
Addon version: 5.1.0
Realm: China

When I checked the in-game dungeon guide, I found some differences between the in-game dungeon guide and the addon.

For example, spell ID 453140:
In the dungeon guide it says 675735 per tick in mythic difficulty, in the addon it says 281799.It seems that it missed some multiplication coefficient.
It's around 1.1^9, but not exactly match.Maybe I missed something.

Here is the screenshot of the game. Maybe it is just a translation or location issue?

![屏幕截图 2024-10-08 151631](https://github.com/user-attachments/assets/a96ee15b-bb08-42ac-82e4-49b639c8e635)

**Comment by Nnoggie** [comment]
The spell tooltips shown in the enemy info window are those of the actual in-game spells. No damage value info is provided by MDT.
