### ISSUE TITLE
MDT Freezes UI with MDT Guide

### ISSUE THREAD

**Issue by dennisaschmidt** [Nnoggie/MythicDungeonTools#616]
When MDT Guide tries to display the minimized window, the map route lines get drawn all over the place, the UI freezes, and I get the following error from MDT:

170x: DrawHullLine: Texture:SetTextCoord(): TexCoord out of range

15/10/24 06:53:46
MDT: 5.1.6
Client: 110002 enUS
Character: Casstìel-WyrmrestAccord (US)
Out of combat
Zone: Isle of Dorn (2339)

Route:
!9HvBZTnUr4FnDA7m5uSi1R9B2Y2tsUlYPNU76h8ewcjckIZKeQaGs2zMJ)27UlaOafvEHwHKAF9zF2DrCY4KFlzJC7FY3z0WTRPNRtUlztM9XnZV5MrXjRJs28tr3enAAY6y89RNacTEAYMvYkEBQM9wBAHOnLzAtnNeMDfJmhFVPGVTP2WRtmWFbJCP1JgpRZ6rthA91CEwB68zJw83AtV7HhF6xFOnDVuuVVnT5a4kj8tbeaR57uYdYsH26Q4bUAYI5JMzD14fZgfDPRURuSVWSvwdwRrZ1TPp)bo7i5QFLdj0x9Utjpz9(kMsjK1TP)hPQs)U20tfIDfW)iklBt5VEOuMbwtK3MwlbG5f49y(iavmIk(O20Ft9M1ShGKceHDcrYCLSYLy7vs0vsf6s0xhu8JczdeFhAYYk5A0kS6xGxu1ObtuXQz7bnFELQPgc7ZXvgNvcIvaPf4Kmwfi3O2p1(js))vB6NDQA18DyuPfgkfVEGbAdGujxHAJ3zXNM9fbOZdQMdOraHV)lBab)zcF6JETP)VgXUxkbNSLNlvucCPf(kKR)IuQ5OyAajyaAYQHp0MgqUtwlXGFQbMdpBKLnmzaBy884rlDSHLr4T9zd3wXugij0nvvYAeBf1c6gGCdV)5FHCRm3Hg3dHYxDXYoM2G0Nhf1iG8bM6ixBC0Nm4wL8nsTQ3zRjehRIP1IJCFDjG2uawf4nqU)rOxcHcNtr5ahLJKJk2RTP3(0dyndA4mcwjQqogtWpziTdHMsRpAuKt7hITP)eC)tFYs3kykqPvRCoJmX)WOyhEp2N9(pwDqj0Y6)PnVyhLImkDmfGJdzvFGIFaq(96cjw5EuXR)2BE4IADnIDqdUYQ93NtDfzdPuqmQpZF6NCqqTrkPuzRudIXRvD4mWZ1ITLChFz6a(s885w2YKOLdzlVjBaK621a7Gv(cyoMMQriIFGTdEdYIjFRLneVs4Nmq6YW4v7Npmc(deLnGnoYXbezI8CXUMsJD2bd793pcng4rqZ)KA8puILAInOz5CBDHxRBqJZrlrd32HsPW2LTuOr8SWULzdY(fr(bNdNqZknfOl3YQf6cKpcXXBq1RRv5EMcCZdVkk54WiQOdyXB(bwkUPrHHdMP8COUsCtEnVsqJ3E(rL8BCqI7e1zAG3SRGjQPMCMc1QZJKTTwDlsZf6d8sQ3jGpERLQ(mU6ceCJbMA4jJ(HN(bFqK0JpEpzXbHuhpCvjesEIOVlRhc4C0leHTNvauHP2Znyk)u9oUhziB0TPRcsDiFnqDUAKRqsnGaSiv1CvWujLehxt(7etyCtGGfLeTdKuGEXUh58(vneg2saKtEwshbgBECeL5dpTW4OrUgL4jZWB7ZwEcyHhf8tas9fFndw2cq0N54rh(Gu(IBq5HgeG20aic67ng8qf5W(UcmbZXJBy5Aesq74WKGgwsb)oyCTr1SdNfBhJJ9whfaq98TNyVG4(kCkcox)R9yi)B)QiE9EIouZp13G9ilFUXiG4G)JMCfiJLP87yAFoR7L0H5AM8u97fDd(PSox8kykxuyBzGWZNlUQZIHvNzZ8vNjlNoAXLvhkKE062vkwo4Z)UgzH4wwfDShIajVY2k8lWPR4Qi5wqR2)6)2(x2iz5Gizw0c)5(Ixgp8Wy3lB2wY94bX7oWG9MLDJpopATBi6jwTJItukAyNm3t1FQFqzs2CIZFHIHUXRVrpwLjWaoxX5W(QmkG9p8j4yA8SKTjB2Y33iqMg(9G1oYkB4OE7AuW(nZxGqhm30UxSbtPJ8sYEkrU5P8Cn3EUB8KXum5K9(MAK2)XSxbKbmHHdZcbxb(fo8dCADOoBHs0dGEiq1DcE)h0xtxX01e6AkE5on(pwiytaEnhVCNP2kT7ivwTXOwwkvaiLhZZZdSTve6CwRhFJTitv51JNtoy8IqdpLeCwO5NeyE04l5bkyfPxSfhQSpT6hHX8azCjXeBi62Unl0IudZ6f9IJLU0CApJyD344qWDb9o3bgUXM62mDmLQO4OlgpXpqnmyZ3AdwAJCakaVLK1xam(hhh8sAaq3dGZdF6YIVRl9AvulKVWttjrSvkaOO8AEO3IUOIbifMDHopUFOtoErxb3xZqVeO1YRyFGp4qix6f)DR8yD3w0CG04a7DgDI6Ho0ikmKIT9mEJXgt1GZIo(cfmeQmaI7CtCp3q)3sjE8WojxkDUfjaQNNmO54mu3RM67SwhB1Y0jyChUhyyYlJxCrc8JhqGu9fjdA16cHyNBTf1zxHSDUVY91OQxRDWdTUe9glzC5fOb68OlH4ZjWckbwsFLDEy)oKW2Ha0W5tsMOETBrxFGAOLJsUwRL3vozSDarttg2hnlK(0zvQ0ffoDo4BDV0gqr9vmUxsCLgRZwLYWzx4csZOl55Nt7RxK72rq)6G63rTo66Kou8lki2qlQ3KLOPxXJbBLiHJ7vNJhF1G0VPXAX4OVJDj(iT42WFf(8o7VTlRiFbokOXW)yDUeZuwJrUcFpUi)UlKbx0t76AezjBk)z9bgVE(3(dm1t()d
Stacktraces

TableToString:
[string "@Interface/AddOns/MythicDungeonTools/Modules/ErrorHandling.lua"]:283: in function `DrawHullLine'
[string "@Interface/AddOns/MythicDungeonTools/Modules/PullOutlines.lua"]:309: in function <...e/AddOns/MythicDungeonTools/Modules/PullOutlines.lua:293>
[string "@Interface/AddOns/MDTGuide/Main.lua"]:864: in function <Interface/AddOns/MDTGuide/Main.lua:853>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/MythicDungeonTools/Modules/ErrorHandling.lua"]:278: in function `DrawHull'
[string "@Interface/AddOns/MythicDungeonTools/Modules/PullOutlines.lua"]:440: in function <...e/AddOns/MythicDungeonTools/Modules/PullOutlines.lua:415>

**Comment by Nnoggie** [comment]
Report the error to the MDT Guide AddOn. It is not affiliated with MDT

**Comment by dennisaschmidt** [comment]
Ok, I will, but it's looks like the PullOutlines in the MDT API that actually crashed according to the stack trace, thought you'd like to know.
