### ISSUE TITLE
Installed Addon, get 30 LUA errors

### ISSUE THREAD

**Issue by VaelyneDH** [Nnoggie/MythicDungeonTools#617]
`Message: Interface/AddOns/MythicDungeonTools/BuildCheck.lua:2: Cannot find a library instance of "AceGUI-3.0".
Time: Wed Oct 16 22:04:48 2024
Count: 1
Stack: Interface/AddOns/MythicDungeonTools/BuildCheck.lua:2: Cannot find a library instance of "AceGUI-3.0".
[string "@Interface/AddOns/DBM-Core/Libs/LibStub/LibStub.lua"]:38: in function `LibStub'
[string "@Interface/AddOns/MythicDungeonTools/BuildCheck.lua"]:2: in main chunk

Locals: self = <table> {
 minors = <table> {
 }
 minor = 2
 libs = <table> {
 }
}
major = "AceGUI-3.0"
silent = nil
`

`Message: ...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:37: Cannot find a library instance of "AceGUI-3.0".
Time: Wed Oct 16 22:04:48 2024
Count: 1
Stack: ...ace/AddOns/MythicDungeonTools/MythicDungeonTools.lua:37: Cannot find a library instance of "AceGUI-3.0".
[string "@Interface/AddOns/DBM-Core/Libs/LibStub/LibStub.lua"]:38: in function `LibStub'
[string "@Interface/AddOns/MythicDungeonTools/MythicDungeonTools.lua"]:37: in main chunk

Locals: self = <table> {
 minors = <table> {
 }
 minor = 2
 libs = <table> {
 }
}
major = "AceGUI-3.0"
silent = nil
`

`Message: ...face/AddOns/MythicDungeonTools/Modules/EnemyInfo.lua:3: Cannot find a library instance of "AceGUI-3.0".
Time: Wed Oct 16 22:04:48 2024
Count: 1
Stack: ...face/AddOns/MythicDungeonTools/Modules/EnemyInfo.lua:3: Cannot find a library instance of "AceGUI-3.0".
[string "@Interface/AddOns/DBM-Core/Libs/LibStub/LibStub.lua"]:38: in function `LibStub'
[string "@Interface/AddOns/MythicDungeonTools/Modules/EnemyInfo.lua"]:3: in main chunk

Locals: self = <table> {
 minors = <table> {
 }
 minor = 2
 libs = <table> {
 }
}
major = "AceGUI-3.0"
silent = nil
`

etc, I do not use curse forge so if there is something more that needs to be done than simply dragging and dropping (extracting) the file into /AddOns/ please lemme know. ty

**Comment by Nnoggie** [comment]
Use Wago / Curseforge to download the AddOn.

**Comment by VaelyneDH** [comment]
so the only way to use your addon is to download unnecessary bloatware? pass, fuck it.
