### ISSUE TITLE
Have any plan to localize another language

### ISSUE THREAD

**Issue by s2quake** [Nnoggie/MythicDungeonTools#82]
I think this add-on is really cool. However, it is inconvenient because the monster's name displayed only in English when talking to party members using the add-on.
If you have any plans to localize another language, please answer me.
For your information, I am playing games in Korea.

**Comment by nnogga** [comment]
Localization will is a feature that will probably follow in a few months.

**Comment by s2quake** [comment]
Thank you for your answer.

**Comment by Nnoggie** [comment]
Localization has now been implemented. Korean translation is still being worked on.
